--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/5/2023 11:14:16 PM
-- Server version: 8.0.32
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS `fly-shoes`;

CREATE DATABASE `fly-shoes`
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE `fly-shoes`;

--
-- Create table `Voucher`
--
CREATE TABLE Voucher (
  VoucherID int NOT NULL AUTO_INCREMENT,
  VoucherTitle varchar(255) NOT NULL DEFAULT '',
  FormulaType int NOT NULL,
  VoucherValue int NOT NULL,
  Quantity int DEFAULT NULL,
  EndDate datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(100) DEFAULT NULL,
  IsActive bit(1) DEFAULT b'0',
  PRIMARY KEY (VoucherID),
  UNIQUE INDEX UK_Voucher_VoucherID (VoucherID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng lưu thông tin voucher';

DELIMITER $$

--
-- Create procedure `Proc_Voucher_Insert`
--
CREATE PROCEDURE Proc_Voucher_Insert (IN v_VoucherTitle varchar(100), IN v_FormulaType int, IN v_VoucherValue int, IN v_Quantity int, IN v_EndDate datetime, IN v_CreatedBy varchar(100), IN v_CreatedDate datetime, IN v_ModifiedDate datetime, IN v_ModifiedBy varchar(100))
SQL SECURITY INVOKER
BEGIN
  INSERT INTO Voucher (VoucherTitle,
  FormulaType,
  VoucherValue,
  Quantity,
  EndDate,
  CreatedBy,
  CreatedDate,
  ModifiedDate,
  ModifiedBy,
  IsActive)
    VALUES (v_VoucherTitle, v_FormulaType, v_VoucherValue, v_Quantity, v_EndDate, v_CreatedBy, v_CreatedDate, v_ModifiedDate, v_ModifiedBy, TRUE);

  SELECT
    LAST_INSERT_ID();
END
$$

--
-- Create procedure `Proc_Voucher_GetALL`
--
CREATE PROCEDURE Proc_Voucher_GetALL ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả voucher'
BEGIN
  SELECT
    v.VoucherID,
    v.VoucherTitle,
    v.VoucherType,
    v.TargetApplyID,
    v.FormulaType,
    v.VoucherValue,
    v.Quantity,
    v.StartDate,
    v.EndDate,
    v.IDApplied
  FROM Voucher v;
END
$$

DELIMITER ;

--
-- Create table `Size`
--
CREATE TABLE Size (
  SizeID int NOT NULL AUTO_INCREMENT,
  SizeName varchar(100) NOT NULL DEFAULT '',
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (SizeID),
  UNIQUE INDEX UK_Size_SizeID (SizeID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng lưu dữ liệu size';

DELIMITER $$

--
-- Create procedure `Proc_Size_GetALL`
--
CREATE PROCEDURE Proc_Size_GetALL ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả size'
BEGIN
  SELECT
    s.SizeID,
    s.SizeName
  FROM Size s;
END
$$

DELIMITER ;

--
-- Create table `PaymentInfo`
--
CREATE TABLE PaymentInfo (
  PaymentInfoID int NOT NULL AUTO_INCREMENT,
  OrderID int NOT NULL,
  BankCode varchar(50) NOT NULL DEFAULT '',
  Amount varchar(50) NOT NULL DEFAULT '',
  TransactionNo varchar(50) NOT NULL DEFAULT '',
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(100) DEFAULT NULL,
  PRIMARY KEY (PaymentInfoID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 53,
AVG_ROW_LENGTH = 546,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `Proc_PaymentInfo_Insert`
--
CREATE PROCEDURE Proc_PaymentInfo_Insert (IN v_OrderID int, IN v_BankCode varchar(50), IN v_Amount varchar(50), IN v_TransactionNo varchar(50), IN v_CreatedDate datetime, IN v_CreatedBy varchar(100), IN v_ModifiedDate datetime, IN v_ModifiedBy varchar(100))
SQL SECURITY INVOKER
BEGIN
  INSERT INTO PaymentInfo (OrderID,
  BankCode,
  Amount,
  TransactionNo,
  CreatedDate)
    VALUES (v_OrderID, v_BankCode, v_Amount, v_TransactionNo, v_CreatedDate);

  SELECT
    LAST_INSERT_ID();
END
$$

DELIMITER ;

--
-- Create table `OrderShoes`
--
CREATE TABLE OrderShoes (
  OrderID int NOT NULL AUTO_INCREMENT,
  UserID int NOT NULL,
  Status int NOT NULL,
  ReceiverName varchar(100) NOT NULL DEFAULT '',
  ReceiverPhone varchar(11) NOT NULL DEFAULT '',
  ReceiverAddress varchar(255) NOT NULL DEFAULT '',
  CreatedBy varchar(100) DEFAULT NULL,
  CreatedDate datetime DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate datetime DEFAULT CURRENT_TIMESTAMP,
  ModifiedBy varchar(100) DEFAULT NULL,
  PaymentMethod int NOT NULL DEFAULT 1,
  PaymentStatus bit(1) NOT NULL DEFAULT b'0',
  TotalBill decimal(19, 0) DEFAULT NULL,
  PRIMARY KEY (OrderID),
  UNIQUE INDEX UK_Order_OrderID (OrderID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 49,
AVG_ROW_LENGTH = 655,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng lưu đơn hàng';

DELIMITER $$

--
-- Create procedure `Proc_Report_Order`
--
CREATE PROCEDURE Proc_Report_Order (IN v_Year int, IN v_Month int, IN v_Monday int, IN v_Sunday int, IN v_TimeAnalyst int)
SQL SECURITY INVOKER
BEGIN
  IF v_TimeAnalyst = 1
    OR v_TimeAnalyst = 2 THEN
    SELECT
      COUNT(OrderID) AS Total,
      DAY(CreatedDate) AS Title
    FROM OrderShoes
    WHERE Status IN (1, 2, 4)
    AND YEAR(CreatedDate) = v_Year
    AND MONTH(CreatedDate) = v_Month
    AND DAY(CreatedDate) BETWEEN v_Monday AND v_Sunday
    GROUP BY DAY(CreatedDate);
  ELSEIF v_TimeAnalyst = 3
    OR v_TimeAnalyst = 4 THEN
    SELECT
      COUNT(os.OrderID) AS Total,
      DAY(os.CreatedDate) AS Title
    FROM OrderShoes os
    WHERE Status IN (1, 2, 4)
    AND YEAR(os.CreatedDate) = v_Year
    AND MONTH(os.CreatedDate) = v_Month
    GROUP BY DAY(CreatedDate);
  ELSE
    SELECT
      COUNT(os.OrderID) AS Total,
      MONTH(os.CreatedDate) AS Title
    FROM OrderShoes os
    WHERE Status IN (1, 2, 4)
    AND YEAR(os.CreatedDate) = v_Year
    GROUP BY MONTH(os.CreatedDate);
  END IF;
END
$$

--
-- Create procedure `Proc_Report_InCome`
--
CREATE PROCEDURE Proc_Report_InCome (IN v_Year int, IN v_Month int, IN v_Monday int, IN v_Sunday int, IN v_TimeAnalyst int)
SQL SECURITY INVOKER
BEGIN
  IF v_TimeAnalyst = 1
    OR v_TimeAnalyst = 2 THEN
    SELECT
      SUM(TotalBill) AS Total,
      DAY(CreatedDate) AS Title
    FROM OrderShoes
    WHERE Status IN (1, 2, 4)
    AND YEAR(CreatedDate) = v_Year
    AND MONTH(CreatedDate) = v_Month
    AND DAY(CreatedDate) BETWEEN v_Monday AND v_Sunday
    GROUP BY DAY(CreatedDate);
  ELSEIF v_TimeAnalyst = 3
    OR v_TimeAnalyst = 4 THEN
    SELECT
      SUM(os.TotalBill) AS Total,
      DAY(os.CreatedDate) AS Title
    FROM OrderShoes os
    WHERE Status IN (1, 2, 4)
    AND YEAR(os.CreatedDate) = v_Year
    AND MONTH(os.CreatedDate) = v_Month
    GROUP BY DAY(CreatedDate);
  ELSE
    SELECT
      SUM(os.TotalBill) AS Total,
      MONTH(os.CreatedDate) AS Title
    FROM OrderShoes os
    WHERE Status IN (1, 2, 4)
    AND YEAR(os.CreatedDate) = v_Year
    GROUP BY MONTH(os.CreatedDate);
  END IF;
END
$$

--
-- Create procedure `Proc_Report_Customer`
--
CREATE PROCEDURE Proc_Report_Customer (IN v_Year int, IN v_Month int, IN v_Monday int, IN v_Sunday int, IN v_TimeAnalyst int)
SQL SECURITY INVOKER
BEGIN
  IF v_TimeAnalyst = 1
    OR v_TimeAnalyst = 2 THEN
    SELECT
      COUNT(os.UserID) AS Total,
      DAY(os.CreatedDate) AS Title
    FROM OrderShoes AS os
    WHERE Status IN (1, 2, 4)
    AND YEAR(os.CreatedDate) = v_Year
    AND MONTH(os.CreatedDate) = v_Month
    AND DAY(os.CreatedDate) BETWEEN v_Monday AND v_Sunday
    GROUP BY os.UserID,
             DAY(os.CreatedDate);
  ELSEIF v_TimeAnalyst = 3
    OR v_TimeAnalyst = 4 THEN
    SELECT
      COUNT(os.UserID) AS Total,
      DAY(os.CreatedDate) AS Title
    FROM OrderShoes os
    WHERE Status IN (1, 2, 4)
    AND YEAR(os.CreatedDate) = v_Year
    AND MONTH(os.CreatedDate) = v_Month
    GROUP BY os.UserID,
             DAY(CreatedDate);
  ELSE
    SELECT
      COUNT(os.UserID) AS Total,
      MONTH(os.CreatedDate) AS Title
    FROM OrderShoes os
    WHERE Status IN (1, 2, 4)
    AND YEAR(os.CreatedDate) = v_Year
    GROUP BY os.UserID,
             MONTH(os.CreatedDate);
  END IF;
END
$$

--
-- Create procedure `Proc_OrderShoes_Insert`
--
CREATE PROCEDURE Proc_OrderShoes_Insert (IN v_UserID int, IN v_Status int, IN v_ReceiverName varchar(100), IN v_ReceiverPhone varchar(100), IN v_ReceiverAddress varchar(255), IN v_TotalBill varchar(255))
SQL SECURITY INVOKER
BEGIN
  INSERT INTO OrderShoes (UserID,
  Status,
  ReceiverName,
  ReceiverPhone,
  ReceiverAddress,
  CreatedBy,
  CreatedDate,
  ModifiedDate,
  ModifiedBy,
  TotalBill)
    VALUES (v_UserID, v_Status, v_ReceiverName, v_ReceiverPhone, v_ReceiverAddress, v_UserID, NOW(), NOW(), v_UserID, v_TotalBill);

  SELECT
    LAST_INSERT_ID();
END
$$

--
-- Create procedure `Proc_OrderShoes_GetByID`
--
CREATE PROCEDURE Proc_OrderShoes_GetByID (IN v_ID int)
SQL SECURITY INVOKER
BEGIN
  SELECT
    *
  FROM OrderShoes os
  WHERE os.OrderID = v_ID;
END
$$

--
-- Create procedure `Proc_Order_GetALL`
--
CREATE PROCEDURE Proc_Order_GetALL ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả đơn hàng'
BEGIN
  SELECT
    o.OrderID,
    o.UserID,
    o.Status,
    o.ReceiverName,
    o.ReceiverPhone,
    o.ReceiverAddress
  FROM OrderShoes o;
END
$$

DELIMITER ;

--
-- Create table `OrderDetail`
--
CREATE TABLE OrderDetail (
  OrderDetailID int NOT NULL AUTO_INCREMENT,
  ShoesID int NOT NULL,
  ShoesDetailID int NOT NULL,
  OrderID int NOT NULL,
  Quantity int NOT NULL DEFAULT 1,
  VoucherID int DEFAULT NULL,
  CreatedDate datetime DEFAULT CURRENT_TIMESTAMP,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT CURRENT_TIMESTAMP,
  ModifiedBy varchar(255) DEFAULT NULL,
  TotalMoney decimal(19, 0) DEFAULT NULL,
  PRIMARY KEY (OrderDetailID),
  UNIQUE INDEX UK_ShoesOrder_ShoesOrderID (OrderDetailID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 52,
AVG_ROW_LENGTH = 585,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng lưu thông tin những đôi giày được order';

DELIMITER $$

--
-- Create procedure `Proc_Report_Today`
--
CREATE PROCEDURE Proc_Report_Today ()
SQL SECURITY INVOKER
BEGIN
  SET @now = (SELECT
      NOW());
  SET @TotalOrder = (SELECT
      COUNT(1)
    FROM OrderShoes os
  --     WHERE YEAR(os.CreatedDate) = YEAR(@now)
  --     AND MONTH(os.CreatedDate) = MONTH(@now)
  --     AND DAY(os.CreatedDate) = DAY(@now)
  );

  SET @TotalProduct = (SELECT
      SUM(od.Quantity)
    FROM OrderDetail od
      INNER JOIN OrderShoes os
        ON od.OrderID = os.OrderID
  --     WHERE YEAR(os.CreatedDate) = YEAR(@now)
  --     AND MONTH(os.CreatedDate) = MONTH(@now)
  --     AND DAY(os.CreatedDate) = DAY(@now)
  );

  SET @TotalMoney = (SELECT
      SUM(os.TotalBill)
    FROM OrderShoes os
  --     WHERE YEAR(os.CreatedDate) = YEAR(@now)
  --     AND MONTH(os.CreatedDate) = MONTH(@now)
  --     AND DAY(os.CreatedDate) = DAY(@now)
  );

  SET @TotalCustomer = (SELECT
      COUNT(1)
    FROM (SELECT DISTINCT
        os.UserID
      FROM OrderShoes os
    --     WHERE YEAR(os.CreatedDate) = YEAR(@now)
    --     AND MONTH(os.CreatedDate) = MONTH(@now)
    --     AND DAY(os.CreatedDate) = DAY(@now)
    ) AS temp);

  SELECT
    @TotalOrder AS TotalOrder,
    IFNULL(@TotalProduct, 0) AS TotalProduct,
    IFNULL(@TotalMoney, 0) AS TotalMoney,
    @TotalCustomer AS TotalCustomer;
END
$$

DELIMITER ;

--
-- Create table `EmailTemplate`
--
CREATE TABLE EmailTemplate (
  EmailTemplateID int NOT NULL AUTO_INCREMENT,
  EmailType int NOT NULL,
  EmailContent text DEFAULT NULL,
  PRIMARY KEY (EmailTemplateID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `Proc_WebInfo_GetALL`
--
CREATE PROCEDURE Proc_WebInfo_GetALL ()
SQL SECURITY INVOKER
BEGIN
  SELECT
    *
  FROM EmailTemplate;
END
$$

--
-- Create procedure `Proc_EmailTemplate_Update`
--
CREATE PROCEDURE Proc_EmailTemplate_Update (IN v_EmailTemplateID int, IN v_EmailType int, IN v_EmailContent text)
SQL SECURITY INVOKER
BEGIN
  UPDATE EmailTemplate et
  SET EmailContent = v_EmailContent
  WHERE EmailTemplateID = v_EmailTemplateID;
END
$$

--
-- Create procedure `Proc_EmailTemplate_GetALL`
--
CREATE PROCEDURE Proc_EmailTemplate_GetALL ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả mẫu email'
BEGIN
  SELECT
    et.EmailTemplateID,
    et.EmailType,
    et.EmailContent
  FROM EmailTemplate et;
END
$$

DELIMITER ;

--
-- Create table `Color`
--
CREATE TABLE Color (
  ColorID int NOT NULL AUTO_INCREMENT,
  ColorName varchar(100) NOT NULL DEFAULT '',
  ColorCode varchar(10) NOT NULL DEFAULT '',
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(100) DEFAULT NULL,
  PRIMARY KEY (ColorID),
  UNIQUE INDEX UK_Color_ColorID (ColorID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng lưu thông tin giày';

DELIMITER $$

--
-- Create procedure `Proc_ShoesDetail_GetByShoesID`
--
CREATE DEFINER = 'dbmasteruser'@'%'
PROCEDURE Proc_ShoesDetail_GetByShoesID (IN v_ShoesID int)
COMMENT 'Lấy chi tiết giày theo id của giày'
BEGIN
  SELECT
    sd.ShoesDetailID,
    sd.SizeName,
    sd.SizeID,
    sd.SizeName,
    sd.ColorID,
    sd.ColorName,
    c.ColorCode,
    c.Description
  FROM ShoesDetail sd
    INNER JOIN Color c
      ON sd.ColorID = c.ColorID
  WHERE sd.ShoesID = v_ShoesID;
END
$$

--
-- Create procedure `Proc_Color_GetALL`
--
CREATE PROCEDURE Proc_Color_GetALL ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả màu'
BEGIN
  SELECT
    c.ColorID,
    c.ColorName,
    c.ColorCode
  FROM Color c;
END
$$

DELIMITER ;

--
-- Create table `Category`
--
CREATE TABLE Category (
  CategoryID int NOT NULL AUTO_INCREMENT,
  CategoryName varchar(100) NOT NULL DEFAULT '',
  CategoryDescription varchar(255) DEFAULT NULL,
  VoucherID varchar(255) DEFAULT NULL,
  CreatedDate datetime DEFAULT CURRENT_TIMESTAMP,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(100) DEFAULT NULL,
  PRIMARY KEY (CategoryID),
  UNIQUE INDEX UK_Category_CategoryID (CategoryID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng thông tin thể loại';

DELIMITER $$

--
-- Create procedure `Proc_Category_GetALL`
--
CREATE PROCEDURE Proc_Category_GetALL ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả thể loại'
BEGIN
  SELECT
    c.CategoryID,
    c.CategoryName,
    c.CategoryDescription
  FROM Category c;
END
$$

DELIMITER ;

--
-- Create table `CartDetail`
--
CREATE TABLE CartDetail (
  CartDetailID int NOT NULL AUTO_INCREMENT,
  UserID int NOT NULL,
  CreatedDate datetime DEFAULT CURRENT_TIMESTAMP,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT CURRENT_TIMESTAMP,
  ModifiedBy varchar(100) DEFAULT NULL,
  ShoesID int NOT NULL,
  PRIMARY KEY (CartDetailID),
  UNIQUE INDEX UK_CartDetail (CartDetailID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 35,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng lưu thông tin giở hàng của khách hàng';

DELIMITER $$

--
-- Create procedure `Proc_CartDetail_Insert`
--
CREATE DEFINER = 'dbmasteruser'@'%'
PROCEDURE Proc_CartDetail_Insert (IN v_UserID int, IN v_ShoesID varchar(255), IN v_CreatedBy varchar(100), IN v_CreatedDate datetime, IN v_ModifiedDate datetime, IN v_ModifiedBy varchar(100))
COMMENT 'Thêm mới sản phẩm vào giỏ hàng'
BEGIN
  INSERT INTO CartDetail (UserID,
  ShoesID,
  CreatedDate,
  CreatedBy,
  ModifiedDate,
  ModifiedBy)
    VALUES (v_UserID, v_ShoesID, NOW(), v_CreatedBy, NOW(), v_CreatedBy);
END
$$

DELIMITER ;

--
-- Create table `ShoesDetail`
--
CREATE TABLE ShoesDetail (
  ShoesDetailID int NOT NULL AUTO_INCREMENT,
  ShoesID int NOT NULL,
  SizeID int NOT NULL,
  ColorID int NOT NULL,
  Quantity int NOT NULL,
  CreatedDate datetime DEFAULT CURRENT_TIMESTAMP,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT CURRENT_TIMESTAMP,
  ModifiedBy varchar(255) DEFAULT NULL,
  ColorName varchar(100) DEFAULT NULL,
  SizeName varchar(100) DEFAULT NULL,
  ColorCode varchar(10) DEFAULT NULL,
  PRIMARY KEY (ShoesDetailID),
  UNIQUE INDEX UK_ShoesDetail_ShoesDetailID (ShoesDetailID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 335,
AVG_ROW_LENGTH = 126,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng lưu thông tin chi tiết giày';

--
-- Create table `Shoes`
--
CREATE TABLE Shoes (
  ShoesID int NOT NULL AUTO_INCREMENT,
  ShoesName varchar(255) NOT NULL DEFAULT '',
  Price decimal(19, 2) NOT NULL,
  ShoesImages text NOT NULL,
  CategoryID int NOT NULL,
  BrandID int NOT NULL,
  CreatedDate datetime DEFAULT CURRENT_TIMESTAMP,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT CURRENT_TIMESTAMP,
  ModifiedBy varchar(100) DEFAULT NULL,
  CategoryName varchar(100) DEFAULT NULL,
  BrandName varchar(100) DEFAULT NULL,
  VoucherID int DEFAULT NULL,
  PRIMARY KEY (ShoesID),
  UNIQUE INDEX UK_Shoes_ShoesID (ShoesID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 152,
AVG_ROW_LENGTH = 1456,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng lưu thông tin giày';

--
-- Create index `IDX_Shoes_BrandID` on table `Shoes`
--
ALTER TABLE Shoes
ADD INDEX IDX_Shoes_BrandID (BrandID);

--
-- Create index `IDX_Shoes_CategoryID` on table `Shoes`
--
ALTER TABLE Shoes
ADD INDEX IDX_Shoes_CategoryID (CategoryID);

--
-- Create index `IDX_Shoes_Price` on table `Shoes`
--
ALTER TABLE Shoes
ADD INDEX IDX_Shoes_Price (Price);

--
-- Create index `IDX_Shoes_ShoesName` on table `Shoes`
--
ALTER TABLE Shoes
ADD INDEX IDX_Shoes_ShoesName (ShoesName);

DELIMITER $$

--
-- Create procedure `Proc_ShoesDetail_GetALL`
--
CREATE PROCEDURE Proc_ShoesDetail_GetALL ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả chi tiết giày'
BEGIN
  SELECT
    s.ShoesName,
    s.ShoesID,
    s.Price,
    s.BrandName,
    s.CategoryName,
    sd.ShoesDetailID,
    sd.SizeName,
    sd.SizeID,
    sd.ColorID,
    sd.ColorName
  FROM ShoesDetail sd
    INNER JOIN Shoes s
      ON sd.ShoesID = s.ShoesID;
END
$$

--
-- Create procedure `Proc_Shoes_Insert`
--
CREATE PROCEDURE Proc_Shoes_Insert (IN v_ShoesName varchar(255), IN v_Price decimal(19, 2), IN v_ShoesImages text, IN v_CategoryID int, IN v_BrandID int, IN v_CategoryName varchar(100), IN v_BrandName varchar(100))
SQL SECURITY INVOKER
BEGIN
  INSERT INTO Shoes (ShoesName, Price, ShoesImages, CategoryID, BrandID, CategoryName, BrandName)
    VALUES (v_ShoesName, v_Price, v_ShoesImages, v_CategoryID, v_BrandID, v_CategoryName, v_BrandName);

  SELECT
    LAST_INSERT_ID();
END
$$

--
-- Create procedure `Proc_Shoes_GetByID`
--
CREATE DEFINER = 'dbmasteruser'@'%'
PROCEDURE Proc_Shoes_GetByID (IN v_ID int)
COMMENT 'Lấy thông tin giày theo id'
BEGIN
  SELECT
    *
  FROM Shoes s
  WHERE s.ShoesID = v_ID;
END
$$

--
-- Create procedure `Proc_Shoes_GetALL`
--
CREATE PROCEDURE Proc_Shoes_GetALL ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả giày'
BEGIN
  SELECT
    *
  FROM Shoes s
  ORDER BY s.ModifiedDate DESC;
END
$$

--
-- Create procedure `Proc_Report_Product`
--
CREATE PROCEDURE Proc_Report_Product (IN v_Year int, IN v_Month int, IN v_Monday int, IN v_Sunday int, IN v_TimeAnalyst int)
SQL SECURITY INVOKER
BEGIN
  IF v_TimeAnalyst = 1
    OR v_TimeAnalyst = 2 THEN
    SELECT
      SUM(od.Quantity) AS Total,
      s.ShoesName AS Title
    FROM OrderDetail od
      INNER JOIN Shoes s
        ON od.ShoesID = s.ShoesID
    WHERE od.OrderID IN (SELECT DISTINCT
        OrderID
      FROM OrderShoes
      WHERE Status IN (1, 2, 4)
      AND YEAR(CreatedDate) = v_Year
      AND MONTH(CreatedDate) = v_Month
      AND DAY(CreatedDate) BETWEEN v_Monday AND v_Sunday
      GROUP BY OrderID,
               DAY(CreatedDate))
    GROUP BY od.ShoesID,
             s.ShoesName;
  ELSEIF v_TimeAnalyst = 3
    OR v_TimeAnalyst = 4 THEN
    SELECT
      SUM(od.Quantity) AS Total,
      s.ShoesName AS Title
    FROM OrderDetail od
      INNER JOIN Shoes s
        ON od.ShoesID = s.ShoesID
    WHERE od.OrderID IN (SELECT
        os.OrderID
      FROM OrderShoes os
      WHERE YEAR(os.CreatedDate) = v_Year
      AND MONTH(os.CreatedDate) = v_Month
      GROUP BY os.OrderID,
               DAY(CreatedDate))
    GROUP BY od.ShoesID,
             s.ShoesName;
  ELSE
    SELECT
      SUM(od.Quantity) AS Total,
      s.ShoesName AS Title
    FROM OrderDetail od
      INNER JOIN Shoes s
        ON od.ShoesID = s.ShoesID
    WHERE od.OrderID IN (SELECT
        os.OrderID
      FROM OrderShoes os
      WHERE YEAR(os.CreatedDate) = v_Year
      GROUP BY os.OrderID,
               MONTH(os.CreatedDate))
    GROUP BY od.ShoesID,
             s.ShoesName;
  END IF;
END
$$

--
-- Create procedure `Proc_OrderDetail_GetALL`
--
CREATE PROCEDURE Proc_OrderDetail_GetALL ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả giày trong hóa đơn'
BEGIN
  SELECT
    od.OrderDetailID,
    temp.ShoesID,
    temp.ShoesDetailID,
    temp.ShoesName,
    temp.ShoesImage,
    od.Quatity,
    temp.ColorName,
    temp.SizeName,
    temp.Price
  FROM OrderDetail od
    INNER JOIN (SELECT
        s.ShoesID,
        sd.ShoesDetailID,
        s.ShoesName,
        s.ShoesImage,
        s.Price,
        sd.ColorName,
        sd.SizeName
      FROM ShoesDetail sd
        INNER JOIN Shoes s
          ON sd.ShoesID = s.ShoesID) AS temp
      ON od.ShoesDetailID = temp.ShoesDetailID;
END
$$

--
-- Create procedure `Proc_CartDetail_GetByUser`
--
CREATE PROCEDURE Proc_CartDetail_GetByUser (IN v_UserID int)
SQL SECURITY INVOKER
BEGIN
  SELECT
    s.ShoesImages,
    s.ShoesID,
    s.ShoesName,
    s.VoucherID,
    s.Price,
    sd.Total,
    sd.CartDetailID
  FROM Shoes s
    INNER JOIN (SELECT
        SUM(sd.Quantity) AS Total,
        cd.CartDetailID,
        cd.UserID,
        cd.ShoesID
      FROM ShoesDetail sd
        INNER JOIN CartDetail cd
          ON sd.ShoesID = cd.ShoesID
      GROUP BY cd.UserID,
               cd.CartDetailID,
               cd.ShoesID) AS sd
      ON sd.ShoesID = s.ShoesID
  WHERE sd.UserID = v_UserID;
END
$$

DELIMITER ;

--
-- Create table `Brand`
--
CREATE TABLE Brand (
  BrandID int NOT NULL AUTO_INCREMENT,
  BrandName varchar(100) NOT NULL DEFAULT '',
  BrandSlogan varchar(255) DEFAULT NULL,
  DescriptionShot varchar(255) DEFAULT NULL,
  DescriptionDetail text DEFAULT NULL,
  BrandLogo varchar(255) NOT NULL DEFAULT '',
  CreatedDate datetime DEFAULT CURRENT_TIMESTAMP,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT CURRENT_TIMESTAMP,
  ModifiedBy varchar(255) DEFAULT NULL,
  VoucherID int DEFAULT NULL,
  PRIMARY KEY (BrandID),
  UNIQUE INDEX UK_Brand_BrandID (BrandID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng lưu thông tin thương hiệu';

DELIMITER $$

--
-- Create procedure `Proc_Brand_GetByID`
--
CREATE PROCEDURE Proc_Brand_GetByID (IN v_ID int)
SQL SECURITY INVOKER
COMMENT 'Lấy thương hiệu theo id'
BEGIN
  SELECT
    *
  FROM Brand b
  WHERE b.BrandID = v_ID;
END
$$

--
-- Create procedure `Proc_Brand_GetALL`
--
CREATE PROCEDURE Proc_Brand_GetALL ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả thương hiệu'
BEGIN

  SELECT
    BrandID,
    BrandName,
    BrandSlogan,
    DescriptionShot,
    DescriptionDetail,
    BrandLogo
  FROM Brand b;

END
$$

DELIMITER ;

--
-- Create table `VoucherUsed`
--
CREATE TABLE VoucherUsed (
  VoucherUsedID int NOT NULL AUTO_INCREMENT,
  VoucherID int DEFAULT NULL,
  UserID int DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedBy varchar(100) DEFAULT NULL,
  PRIMARY KEY (VoucherUsedID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Voucher đã được sử dụng';

--
-- Create table `User`
--
CREATE TABLE User (
  UserID int NOT NULL AUTO_INCREMENT,
  FullName varchar(100) NOT NULL DEFAULT '',
  Email varchar(50) NOT NULL DEFAULT '',
  FirebaseID varchar(50) NOT NULL DEFAULT '',
  Address varchar(255) DEFAULT NULL,
  IsAdmin bit(1) DEFAULT b'0',
  AmountSpent decimal(19, 2) DEFAULT NULL,
  Phone varchar(255) DEFAULT NULL,
  CreatedDate datetime DEFAULT CURRENT_TIMESTAMP,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(100) DEFAULT NULL,
  ReceiveEmail bit(1) DEFAULT b'0',
  IsUsePassword bit(1) DEFAULT b'0',
  PRIMARY KEY (UserID),
  UNIQUE INDEX UK_User_UserID (UserID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 23,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng lưu thông tin user';

--
-- Create index `UK_User_FirebaseId` on table `User`
--
ALTER TABLE User
ADD UNIQUE INDEX UK_User_FirebaseId (FirebaseID);

DELIMITER $$

--
-- Create procedure `Proc_User_Update`
--
CREATE PROCEDURE Proc_User_Update (IN v_Email varchar(100), IN v_Address varbinary(255), IN v_FullName varchar(100), IN v_Phone varchar(20), IN v_UserID int, IN v_FirebaseID varchar(50), IN v_AmountSpent decimal(10, 0), IN v_ReceiveEmail bit, IN v_CreatedBy varchar(100), IN v_CreatedDate datetime, IN v_ModifiedDate datetime, IN v_ModifiedBy varchar(100))
SQL SECURITY INVOKER
BEGIN
  UPDATE User u
  SET Email = v_Email,
      Address = v_Address,
      FullName = v_FullName,
      Phone = v_Phone
  WHERE u.UserID = v_UserID;
END
$$

--
-- Create procedure `Proc_User_Insert`
--
CREATE PROCEDURE Proc_User_Insert (IN v_FullName varchar(100), IN v_Email varchar(100), IN v_FirebaseID varchar(50))
SQL SECURITY INVOKER
BEGIN
  INSERT INTO User (FullName, FirebaseID, Email, CreatedDate, ModifiedDate, IsAdmin, AmountSpent)
    VALUES (v_FullName, v_FirebaseID, v_Email, NOW(), NOW(), FALSE, 0);
END
$$

--
-- Create procedure `Proc_User_GetByID`
--
CREATE PROCEDURE Proc_User_GetByID (IN v_ID int)
SQL SECURITY INVOKER
BEGIN
  SELECT
    *
  FROM User u
  WHERE u.UserID = v_ID;
END
$$

--
-- Create procedure `Proc_User_GetALL`
--
CREATE PROCEDURE Proc_User_GetALL ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả người dùng'
BEGIN
  SELECT
    u.UserID,
    u.FullName,
    u.Email,
    u.FirebaseId,
    u.Address,
    u.IsAdmin,
    u.RankID,
    u.AmountSpent,
    u.Phone
  FROM User u;
END
$$

--
-- Create procedure `Proc_Shoes_Paging`
--
CREATE PROCEDURE Proc_Shoes_Paging (IN v_WhereClause text, IN v_SearchClause text, IN v_PageSize int, IN v_PageIndex int, IN v_SortOrder text, IN v_Table varchar(100))
SQL SECURITY INVOKER
COMMENT 'Lấy paging cho giày'
BEGIN
  IF (v_WhereClause IS NOT NULL
    OR v_SearchClause IS NOT NULL) THEN
    SET @where = CONCAT('WHERE ', IF(v_WhereClause IS NULL OR v_WhereClause = '', '', CONCAT(v_WhereClause, ' AND ')), IF(v_SearchClause IS NULL OR v_SearchClause = '', '1 = 1', v_SearchClause));
  ELSE
    SET @where = '';
  END IF;

  IF (v_SortOrder IS NULL) THEN
    SET @sortOrder = 'ModifiedDate DESC';
  ELSE
    SET @sortOrder = v_SortOrder;
  END IF;

  SET @sqlPaging = CONCAT('SELECT * FROM ', v_Table, ' ', @where, ' ORDER BY ', @sortOrder, ' LIMIT ', v_PageSize, ' OFFSET ', v_PageSize * (v_PageIndex - 1), ';');

  PREPARE paging FROM @sqlPaging;
  EXECUTE paging;
  DEALLOCATE PREPARE paging;
END
$$

--
-- Create procedure `Proc_RankCustomer_GetALL`
--
CREATE PROCEDURE Proc_RankCustomer_GetALL ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả cấp bậc của khách hàng'
BEGIN
  SELECT
    rc.RankID,
    rc.RankName,
    rc.Min,
    rc.Max,
    rc.Level
  FROM RankCustomer rc;
END
$$

--
-- Create procedure `Proc_Paging`
--
CREATE PROCEDURE Proc_Paging (IN v_WhereClause text, IN v_SearchClause text, IN v_PageSize int, IN v_PageIndex int, IN v_SortOrder text, IN v_Table varchar(100))
SQL SECURITY INVOKER
COMMENT 'Lấy paging cho giày'
BEGIN
  IF (v_WhereClause IS NOT NULL
    OR v_SearchClause IS NOT NULL) THEN
    SET @where = CONCAT('WHERE ', IF(v_WhereClause IS NULL OR v_WhereClause = '', '', CONCAT(v_WhereClause, ' AND ')), IF(v_SearchClause IS NULL OR v_SearchClause = '', '1 = 1', v_SearchClause));
  ELSE
    SET @where = '';
  END IF;

  IF (v_SortOrder IS NULL) THEN
    SET @sortOrder = 'ModifiedDate DESC';
  ELSE
    SET @sortOrder = v_SortOrder;
  END IF;

  SET @sqlPaging = CONCAT('SELECT * FROM ', v_Table, ' ', @where, ' ORDER BY ', @sortOrder, ' LIMIT ', v_PageSize, ' OFFSET ', v_PageSize * (v_PageIndex - 1), ';');

  PREPARE paging FROM @sqlPaging;
  EXECUTE paging;
  DEALLOCATE PREPARE paging;
END
$$

--
-- Create procedure `Proc_GetTotal`
--
CREATE PROCEDURE Proc_GetTotal (IN v_WhereClause text, IN v_SearchClause text, IN v_PageSize int, IN v_PageIndex int, IN v_SortOrder text, IN v_Table varchar(100))
SQL SECURITY INVOKER
COMMENT 'Lấy tổng số bản ghi theo paging'
BEGIN
  IF (v_WhereClause IS NOT NULL
    OR v_SearchClause IS NOT NULL) THEN
    SET @where = CONCAT('WHERE ', IF(v_WhereClause IS NULL OR v_WhereClause = '', '', CONCAT(v_WhereClause, ' AND ')), IF(v_SearchClause IS NULL OR v_SearchClause = '', '1 = 1', v_SearchClause));
  ELSE
    SET @where = '';
  END IF;

  IF (v_SortOrder IS NULL) THEN
    SET v_SortOrder = 'ModifiedDate DESC';
  END IF;

  SET @sqlPaging = CONCAT('SELECT COUNT(1) FROM ', v_Table, ' ', @where, ' ORDER BY ', v_SortOrder);

  PREPARE paging FROM @sqlPaging;
  EXECUTE paging;
  DEALLOCATE PREPARE paging;
END
$$

DELIMITER ;

-- 
-- Dumping data for table VoucherUsed
--
INSERT INTO VoucherUsed VALUES
(5, 6, 12, '2023-04-18 02:36:49', '2023-04-18 02:36:49', 'Lê Mạnh Hùng', 'Lê Mạnh Hùng'),
(7, 6, 6, '2023-04-19 02:12:14', '2023-04-19 02:12:14', 'Hùng Lê', 'Hùng Lê'),
(8, 6, 13, '2023-05-01 10:45:43', '2023-05-01 10:45:43', 'Lê Mạnh Hùng', 'Lê Mạnh Hùng');

-- 
-- Dumping data for table Voucher
--
INSERT INTO Voucher VALUES
(6, 'Giảm giá 30/4', 2, 10, 7, '2023-05-30 17:23:23', '2023-04-13 00:23:47', 'mhung.haui.webdev@gmail.com', '2023-04-13 00:23:47', 'mhung.haui.webdev@gmail.com', True);

-- 
-- Dumping data for table User
--
INSERT INTO User VALUES
(2, 'Vũ Tuấn Anh', 'vut5441@gmail.com', 'g5nMF9RnzuXxK4k1WeZFZUtiL002', 'Bắc Ninh', False, 70000000.00, '(333) 827-8984', '2008-05-20 23:37:32', '"Admin"', '2018-12-05 07:14:12', 'Abram Tirado', True, True),
(4, 'mhung.haui.webdev@gmail.com', 'mhung.haui.webdev@gmail.com', 'tzymwmvr63SF19wg2H24fBdLvXI2', NULL, True, 0.00, NULL, '2023-03-28 16:24:25', NULL, '2023-03-28 16:24:25', NULL, True, False),
(11, 'Nguyễn Huy Hùng', 'akdom@gmail.com', 'gH4W0dt6PnVVqwecI0pkBKXSZOU2', NULL, False, 0.00, NULL, '2023-04-10 20:13:15', NULL, '2023-04-10 20:13:15', NULL, True, True),
(12, 'Lê Mạnh Hùng', 'lmhung@software.misa.com.vn', 'aW399XdVmqORA6s4oJw2lO0RjI63', NULL, False, 5116000.00, NULL, '2023-04-16 07:53:35', NULL, '2023-04-16 07:53:35', NULL, True, True),
(13, 'Lê Mạnh Hùng', 'mhung.haui.webdev@gmail.com', 'ZiOGBAQIz5gWg4lOWnxkxZ68cX63', 'Xã Thanh Mai - Huyện Thanh Oai - Thành phố Hà Nội', False, 5127500.00, '0866940201', '2023-04-18 15:50:42', NULL, '2023-04-18 15:50:42', NULL, True, False),
(19, 'Hùng Lê', '', 'nC5sVRJHGkSjWVyHRkePzCC6CJZ2', NULL, False, 9427500.00, NULL, '2023-04-27 13:13:12', NULL, '2023-04-27 13:13:12', NULL, False, False),
(20, 'N9.Hùng Lê', '', 'd1lp4SjqKrRtBc4D1rFE4skCOPp2', NULL, False, 0.00, NULL, '2023-04-27 13:20:38', NULL, '2023-04-27 13:20:38', NULL, False, False),
(21, 'nam', 'nam@gmail.com', 'R42MwPZcfnfs3QEQyaj3gCJBJEZ2', NULL, False, 0.00, NULL, '2023-04-29 09:00:08', NULL, '2023-04-29 09:00:08', NULL, False, False),
(22, 'hang', 'thuhang@yopmail.com', 'zP2HIHcpguRvA8DKSXUqsteAQR43', NULL, False, 1825000.00, NULL, '2023-05-06 08:43:28', NULL, '2023-05-06 08:43:28', NULL, False, False);

-- 
-- Dumping data for table Size
--
INSERT INTO Size VALUES
(1, '34', '2004-08-15 22:38:50', 'Admin', '2023-04-05 00:00:00', 'Admin'),
(2, '35', '1970-01-01 00:00:02', 'Admin', '2023-04-05 00:00:00', 'Admin'),
(3, '36', '1970-01-01 00:54:29', 'Admin', '2023-04-05 00:00:00', 'Admin'),
(4, '37', '2017-01-20 01:26:30', 'Admin', '2023-04-05 00:00:00', 'Admin'),
(5, '38', '1973-12-22 01:20:50', 'Admin', '2023-04-05 00:00:00', 'Admin'),
(6, '39', '2023-04-05 00:00:00', 'Admin', '2023-04-05 00:00:00', 'Admin'),
(7, '40', '2023-04-05 00:00:00', 'Admin', '2023-04-05 00:00:00', 'Admin'),
(8, '41', '2023-04-05 00:00:00', 'Admin', '2023-04-05 00:00:00', 'Admin'),
(9, '42', '2023-04-05 00:00:00', 'Admin', '2023-04-05 00:00:00', 'Admin');

-- 
-- Dumping data for table ShoesDetail
--
INSERT INTO ShoesDetail VALUES
(205, 107, 7, 5, 20, '2023-04-05 15:53:09', NULL, '2023-04-05 15:53:09', NULL, 'Màu trắng', '40', '#ffffff'),
(206, 107, 8, 5, 20, '2023-04-05 15:53:09', NULL, '2023-04-05 15:53:09', NULL, 'Màu trắng', '41', '#ffffff'),
(207, 107, 9, 5, 20, '2023-04-05 15:53:09', NULL, '2023-04-05 15:53:09', NULL, 'Màu trắng', '42', '#ffffff'),
(208, 108, 8, 4, 20, '2023-04-05 15:56:28', NULL, '2023-04-05 15:56:28', NULL, 'Màu đen', '41', '#000000'),
(209, 108, 9, 4, 20, '2023-04-05 15:56:28', NULL, '2023-04-05 15:56:28', NULL, 'Màu đen', '42', '#000000'),
(210, 109, 1, 4, 20, '2023-04-05 15:59:02', NULL, '2023-04-05 15:59:02', NULL, 'Màu đen', '34', '#000000'),
(211, 110, 8, 2, 20, '2023-04-05 16:00:49', NULL, '2023-04-05 16:00:49', NULL, 'Màu xanh dương', '41', '#0088d6'),
(212, 110, 9, 2, 20, '2023-04-05 16:00:49', NULL, '2023-04-05 16:00:49', NULL, 'Màu xanh dương', '42', '#0088d6'),
(213, 111, 7, 6, 20, '2023-04-05 16:04:14', NULL, '2023-04-05 16:04:14', NULL, 'Màu nâu', '40', '#be7659'),
(214, 111, 9, 1, 10, '2023-04-05 16:04:14', NULL, '2023-04-05 16:04:14', NULL, 'Màu đỏ', '42', '#d61525'),
(215, 111, 9, 6, 10, '2023-04-05 16:04:14', NULL, '2023-04-05 16:04:14', NULL, 'Màu nâu', '42', '#be7659'),
(216, 112, 7, 3, 20, '2023-04-05 16:07:13', NULL, '2023-04-05 16:07:13', NULL, 'Màu xanh lá', '40', '#029c47'),
(217, 112, 7, 4, 20, '2023-04-05 16:07:13', NULL, '2023-04-05 16:07:13', NULL, 'Màu đen', '40', '#000000'),
(218, 112, 8, 4, 15, '2023-04-05 16:07:13', NULL, '2023-04-05 16:07:13', NULL, 'Màu đen', '41', '#000000'),
(219, 112, 8, 3, 15, '2023-04-05 16:07:13', NULL, '2023-04-05 16:07:13', NULL, 'Màu xanh lá', '41', '#029c47'),
(220, 113, 7, 4, 10, '2023-04-05 16:10:02', NULL, '2023-04-05 16:10:02', NULL, 'Màu đen', '40', '#000000'),
(221, 113, 7, 2, 10, '2023-04-05 16:10:02', NULL, '2023-04-05 16:10:02', NULL, 'Màu xanh dương', '40', '#0088d6'),
(222, 113, 7, 5, 10, '2023-04-05 16:10:02', NULL, '2023-04-05 16:10:02', NULL, 'Màu trắng', '40', '#ffffff'),
(223, 113, 8, 5, 15, '2023-04-05 16:10:02', NULL, '2023-04-05 16:10:02', NULL, 'Màu trắng', '41', '#ffffff'),
(224, 113, 8, 4, 15, '2023-04-05 16:10:02', NULL, '2023-04-05 16:10:02', NULL, 'Màu đen', '41', '#000000'),
(225, 113, 8, 2, 15, '2023-04-05 16:10:02', NULL, '2023-04-05 16:10:02', NULL, 'Màu xanh dương', '41', '#0088d6'),
(226, 113, 9, 5, 10, '2023-04-05 16:10:02', NULL, '2023-04-05 16:10:02', NULL, 'Màu trắng', '42', '#ffffff'),
(227, 113, 9, 2, 10, '2023-04-05 16:10:02', NULL, '2023-04-05 16:10:02', NULL, 'Màu xanh dương', '42', '#0088d6'),
(228, 114, 7, 5, 9, '2023-04-05 16:11:46', NULL, '2023-04-05 16:11:46', NULL, 'Màu trắng', '40', '#ffffff'),
(229, 114, 8, 5, 5, '2023-04-05 16:11:46', NULL, '2023-04-05 16:11:46', NULL, 'Màu trắng', '41', '#ffffff'),
(230, 115, 6, 1, 15, '2023-04-05 16:13:13', NULL, '2023-04-05 16:13:13', NULL, 'Màu đỏ', '39', '#d61525'),
(231, 115, 8, 1, 10, '2023-04-05 16:13:13', NULL, '2023-04-05 16:13:13', NULL, 'Màu đỏ', '41', '#d61525'),
(232, 115, 9, 1, 5, '2023-04-05 16:13:13', NULL, '2023-04-05 16:13:13', NULL, 'Màu đỏ', '42', '#d61525'),
(233, 116, 7, 5, 10, '2023-04-05 16:15:38', NULL, '2023-04-05 16:15:38', NULL, 'Màu trắng', '40', '#ffffff'),
(234, 116, 8, 5, 15, '2023-04-05 16:15:38', NULL, '2023-04-05 16:15:38', NULL, 'Màu trắng', '41', '#ffffff'),
(235, 116, 9, 5, 16, '2023-04-05 16:15:38', NULL, '2023-04-05 16:15:38', NULL, 'Màu trắng', '42', '#ffffff'),
(236, 117, 7, 5, 11, '2023-04-05 16:19:10', NULL, '2023-04-05 16:19:10', NULL, 'Màu trắng', '40', '#ffffff'),
(237, 117, 8, 5, 10, '2023-04-05 16:19:10', NULL, '2023-04-05 16:19:10', NULL, 'Màu trắng', '41', '#ffffff'),
(238, 118, 7, 2, 10, '2023-04-05 16:22:06', NULL, '2023-04-05 16:22:06', NULL, 'Màu xanh dương', '40', '#0088d6'),
(239, 118, 8, 2, 12, '2023-04-05 16:22:06', NULL, '2023-04-05 16:22:06', NULL, 'Màu xanh dương', '41', '#0088d6'),
(240, 118, 9, 2, 19, '2023-04-05 16:22:06', NULL, '2023-04-05 16:22:06', NULL, 'Màu xanh dương', '42', '#0088d6'),
(241, 119, 7, 4, 9, '2023-04-05 16:24:01', NULL, '2023-04-05 16:24:01', NULL, 'Màu đen', '40', '#000000'),
(242, 119, 8, 4, 12, '2023-04-05 16:24:01', NULL, '2023-04-05 16:24:01', NULL, 'Màu đen', '41', '#000000'),
(243, 119, 9, 4, 13, '2023-04-05 16:24:01', NULL, '2023-04-05 16:24:01', NULL, 'Màu đen', '42', '#000000'),
(244, 120, 7, 2, 10, '2023-04-05 16:25:36', NULL, '2023-04-05 16:25:36', NULL, 'Màu xanh dương', '40', '#0088d6'),
(245, 120, 7, 5, 10, '2023-04-05 16:25:36', NULL, '2023-04-05 16:25:36', NULL, 'Màu trắng', '40', '#ffffff'),
(246, 120, 8, 2, 12, '2023-04-05 16:25:36', NULL, '2023-04-05 16:25:36', NULL, 'Màu xanh dương', '41', '#0088d6'),
(247, 120, 8, 5, 12, '2023-04-05 16:25:36', NULL, '2023-04-05 16:25:36', NULL, 'Màu trắng', '41', '#ffffff'),
(248, 120, 9, 2, 13, '2023-04-05 16:25:36', NULL, '2023-04-05 16:25:36', NULL, 'Màu xanh dương', '42', '#0088d6'),
(249, 121, 7, 2, 15, '2023-04-05 16:27:24', NULL, '2023-04-05 16:27:24', NULL, 'Màu xanh dương', '40', '#0088d6'),
(250, 121, 8, 2, 12, '2023-04-05 16:27:24', NULL, '2023-04-05 16:27:24', NULL, 'Màu xanh dương', '41', '#0088d6'),
(251, 122, 7, 4, 10, '2023-04-05 16:33:07', NULL, '2023-04-05 16:33:07', NULL, 'Màu đen', '40', '#000000'),
(252, 122, 8, 1, 15, '2023-04-05 16:33:07', NULL, '2023-04-05 16:33:07', NULL, 'Màu đỏ', '41', '#d61525'),
(253, 122, 8, 4, 15, '2023-04-05 16:33:07', NULL, '2023-04-05 16:33:07', NULL, 'Màu đen', '41', '#000000'),
(254, 122, 9, 4, 12, '2023-04-05 16:33:07', NULL, '2023-04-05 16:33:07', NULL, 'Màu đen', '42', '#000000'),
(255, 123, 7, 2, 9, '2023-04-05 16:35:22', NULL, '2023-04-05 16:35:22', NULL, 'Màu xanh dương', '40', '#0088d6'),
(256, 123, 8, 2, 12, '2023-04-05 16:35:22', NULL, '2023-04-05 16:35:22', NULL, 'Màu xanh dương', '41', '#0088d6'),
(257, 123, 9, 2, 12, '2023-04-05 16:35:22', NULL, '2023-04-05 16:35:22', NULL, 'Màu xanh dương', '42', '#0088d6'),
(258, 124, 8, 6, 12, '2023-04-05 16:36:45', NULL, '2023-04-05 16:36:45', NULL, 'Màu nâu', '41', '#be7659'),
(259, 124, 9, 6, 18, '2023-04-05 16:36:45', NULL, '2023-04-05 16:36:45', NULL, 'Màu nâu', '42', '#be7659'),
(260, 125, 9, 6, 26, '2023-04-05 16:37:52', NULL, '2023-04-05 16:37:52', NULL, 'Màu nâu', '42', '#be7659'),
(261, 125, 7, 6, 18, '2023-04-05 16:37:52', NULL, '2023-04-05 16:37:52', NULL, 'Màu nâu', '40', '#be7659'),
(262, 126, 7, 5, 12, '2023-04-05 16:40:21', NULL, '2023-04-05 16:40:21', NULL, 'Màu trắng', '40', '#ffffff'),
(263, 126, 8, 5, 12, '2023-04-05 16:40:21', NULL, '2023-04-05 16:40:21', NULL, 'Màu trắng', '41', '#ffffff'),
(264, 126, 9, 5, 19, '2023-04-05 16:40:21', NULL, '2023-04-05 16:40:21', NULL, 'Màu trắng', '42', '#ffffff'),
(265, 127, 7, 5, 16, '2023-04-05 16:41:48', NULL, '2023-04-05 16:41:48', NULL, 'Màu trắng', '40', '#ffffff'),
(266, 127, 8, 5, 16, '2023-04-05 16:41:48', NULL, '2023-04-05 16:41:48', NULL, 'Màu trắng', '41', '#ffffff'),
(267, 127, 9, 5, 17, '2023-04-05 16:41:48', NULL, '2023-04-05 16:41:48', NULL, 'Màu trắng', '42', '#ffffff'),
(268, 128, 7, 5, 29, '2023-04-05 16:43:32', NULL, '2023-04-05 16:43:32', NULL, 'Màu trắng', '40', '#ffffff'),
(269, 128, 8, 5, 14, '2023-04-05 16:43:32', NULL, '2023-04-05 16:43:32', NULL, 'Màu trắng', '41', '#ffffff'),
(270, 128, 6, 5, 14, '2023-04-05 16:43:32', NULL, '2023-04-05 16:43:32', NULL, 'Màu trắng', '39', '#ffffff'),
(271, 129, 4, 5, 16, '2023-04-05 16:45:05', NULL, '2023-04-05 16:45:05', NULL, 'Màu trắng', '37', '#ffffff'),
(272, 129, 5, 5, 15, '2023-04-05 16:45:05', NULL, '2023-04-05 16:45:05', NULL, 'Màu trắng', '38', '#ffffff'),
(273, 129, 6, 5, 11, '2023-04-05 16:45:05', NULL, '2023-04-05 16:45:05', NULL, 'Màu trắng', '39', '#ffffff'),
(274, 129, 8, 5, 10, '2023-04-05 16:45:05', NULL, '2023-04-05 16:45:05', NULL, 'Màu trắng', '41', '#ffffff'),
(275, 130, 7, 5, 13, '2023-04-05 16:47:21', NULL, '2023-04-05 16:47:21', NULL, 'Màu trắng', '40', '#ffffff'),
(276, 130, 8, 5, 19, '2023-04-05 16:47:21', NULL, '2023-04-05 16:47:21', NULL, 'Màu trắng', '41', '#ffffff'),
(277, 130, 9, 5, 28, '2023-04-05 16:47:21', NULL, '2023-04-05 16:47:21', NULL, 'Màu trắng', '42', '#ffffff'),
(278, 131, 7, 5, 19, '2023-04-05 16:48:42', NULL, '2023-04-05 16:48:42', NULL, 'Màu trắng', '40', '#ffffff'),
(279, 131, 8, 5, 11, '2023-04-05 16:48:42', NULL, '2023-04-05 16:48:42', NULL, 'Màu trắng', '41', '#ffffff'),
(280, 131, 6, 5, 10, '2023-04-05 16:48:42', NULL, '2023-04-05 16:48:42', NULL, 'Màu trắng', '39', '#ffffff'),
(281, 132, 5, 4, 15, '2023-04-05 16:50:50', NULL, '2023-04-05 16:50:50', NULL, 'Màu đen', '38', '#000000'),
(282, 133, 7, 5, 15, '2023-04-05 16:51:51', NULL, '2023-04-05 16:51:51', NULL, 'Màu trắng', '40', '#ffffff'),
(283, 133, 8, 5, 23, '2023-04-05 16:51:51', NULL, '2023-04-05 16:51:51', NULL, 'Màu trắng', '41', '#ffffff'),
(284, 134, 8, 4, 18, '2023-04-05 16:54:37', NULL, '2023-04-05 16:54:37', NULL, 'Màu đen', '41', '#000000'),
(285, 135, 8, 7, 19, '2023-04-05 16:56:43', NULL, '2023-04-05 16:56:43', NULL, 'Màu vàng', '41', '#f3de54'),
(286, 135, 9, 7, 12, '2023-04-05 16:56:43', NULL, '2023-04-05 16:56:43', NULL, 'Màu vàng', '42', '#f3de54'),
(287, 136, 6, 7, 12, '2023-04-05 16:58:02', NULL, '2023-04-05 16:58:02', NULL, 'Màu vàng', '39', '#f3de54'),
(288, 136, 8, 7, 21, '2023-04-05 16:58:02', NULL, '2023-04-05 16:58:02', NULL, 'Màu vàng', '41', '#f3de54'),
(289, 137, 8, 4, 16, '2023-04-05 16:59:57', NULL, '2023-04-05 16:59:57', NULL, 'Màu đen', '41', '#000000'),
(290, 138, 8, 5, 19, '2023-04-05 17:01:39', NULL, '2023-04-05 17:01:39', NULL, 'Màu trắng', '41', '#ffffff'),
(291, 138, 9, 5, 15, '2023-04-05 17:01:39', NULL, '2023-04-05 17:01:39', NULL, 'Màu trắng', '42', '#ffffff'),
(292, 139, 9, 4, 10, '2023-04-05 17:03:41', NULL, '2023-04-05 17:03:41', NULL, 'Màu đen', '42', '#000000'),
(293, 140, 7, 5, 19, '2023-04-05 17:05:29', NULL, '2023-04-05 17:05:29', NULL, 'Màu trắng', '40', '#ffffff'),
(294, 140, 9, 5, 18, '2023-04-05 17:05:29', NULL, '2023-04-05 17:05:29', NULL, 'Màu trắng', '42', '#ffffff'),
(295, 141, 7, 5, 14, '2023-04-05 17:10:30', NULL, '2023-04-05 17:10:30', NULL, 'Màu trắng', '40', '#ffffff'),
(296, 141, 8, 5, 12, '2023-04-05 17:10:30', NULL, '2023-04-05 17:10:30', NULL, 'Màu trắng', '41', '#ffffff'),
(297, 142, 7, 5, 15, '2023-04-05 17:15:01', NULL, '2023-04-05 17:15:01', NULL, 'Màu trắng', '40', '#ffffff'),
(298, 142, 8, 5, 17, '2023-04-05 17:15:01', NULL, '2023-04-05 17:15:01', NULL, 'Màu trắng', '41', '#ffffff'),
(299, 142, 9, 5, 12, '2023-04-05 17:15:01', NULL, '2023-04-05 17:15:01', NULL, 'Màu trắng', '42', '#ffffff'),
(300, 143, 7, 4, 19, '2023-04-05 17:17:05', NULL, '2023-04-05 17:17:05', NULL, 'Màu đen', '40', '#000000'),
(301, 143, 7, 7, 19, '2023-04-05 17:17:05', NULL, '2023-04-05 17:17:05', NULL, 'Màu vàng', '40', '#f3de54'),
(302, 143, 8, 4, 19, '2023-04-05 17:17:05', NULL, '2023-04-05 17:17:05', NULL, 'Màu đen', '41', '#000000'),
(303, 143, 8, 7, 19, '2023-04-05 17:17:05', NULL, '2023-04-05 17:17:05', NULL, 'Màu vàng', '41', '#f3de54'),
(304, 143, 9, 4, 17, '2023-04-05 17:17:05', NULL, '2023-04-05 17:17:05', NULL, 'Màu đen', '42', '#000000'),
(305, 144, 8, 7, 12, '2023-04-05 17:20:19', NULL, '2023-04-05 17:20:19', NULL, 'Màu vàng', '41', '#f3de54'),
(306, 145, 7, 1, 15, '2023-04-05 17:24:06', NULL, '2023-04-05 17:24:06', NULL, 'Màu đỏ', '40', '#d61525'),
(307, 145, 7, 2, 15, '2023-04-05 17:24:06', NULL, '2023-04-05 17:24:06', NULL, 'Màu xanh dương', '40', '#0088d6'),
(308, 145, 8, 1, 12, '2023-04-05 17:24:06', NULL, '2023-04-05 17:24:06', NULL, 'Màu đỏ', '41', '#d61525'),
(309, 145, 8, 2, 12, '2023-04-05 17:24:06', NULL, '2023-04-05 17:24:06', NULL, 'Màu xanh dương', '41', '#0088d6'),
(310, 145, 9, 1, 11, '2023-04-05 17:24:06', NULL, '2023-04-05 17:24:06', NULL, 'Màu đỏ', '42', '#d61525'),
(311, 146, 7, 1, 15, '2023-04-05 17:26:25', NULL, '2023-04-05 17:26:25', NULL, 'Màu đỏ', '40', '#d61525'),
(312, 146, 7, 2, 15, '2023-04-05 17:26:25', NULL, '2023-04-05 17:26:25', NULL, 'Màu xanh dương', '40', '#0088d6'),
(313, 146, 7, 7, 15, '2023-04-05 17:26:25', NULL, '2023-04-05 17:26:25', NULL, 'Màu vàng', '40', '#f3de54'),
(314, 146, 8, 1, 12, '2023-04-05 17:26:25', NULL, '2023-04-05 17:26:25', NULL, 'Màu đỏ', '41', '#d61525'),
(315, 146, 8, 2, 12, '2023-04-05 17:26:25', NULL, '2023-04-05 17:26:25', NULL, 'Màu xanh dương', '41', '#0088d6'),
(316, 146, 8, 7, 12, '2023-04-05 17:26:25', NULL, '2023-04-05 17:26:25', NULL, 'Màu vàng', '41', '#f3de54'),
(317, 146, 9, 1, 11, '2023-04-05 17:26:25', NULL, '2023-04-05 17:26:25', NULL, 'Màu đỏ', '42', '#d61525'),
(318, 146, 9, 2, 11, '2023-04-05 17:26:25', NULL, '2023-04-05 17:26:25', NULL, 'Màu xanh dương', '42', '#0088d6'),
(319, 146, 9, 7, 11, '2023-04-05 17:26:25', NULL, '2023-04-05 17:26:25', NULL, 'Màu vàng', '42', '#f3de54'),
(320, 147, 7, 5, 13, '2023-04-05 17:27:50', NULL, '2023-04-05 17:27:50', NULL, 'Màu trắng', '40', '#ffffff'),
(321, 147, 7, 4, 19, '2023-04-05 17:27:50', NULL, '2023-04-05 17:27:50', NULL, 'Màu đen', '40', '#000000'),
(322, 147, 8, 4, 12, '2023-04-05 17:27:50', NULL, '2023-04-05 17:27:50', NULL, 'Màu đen', '41', '#000000'),
(323, 147, 8, 5, 12, '2023-04-05 17:27:50', NULL, '2023-04-05 17:27:50', NULL, 'Màu trắng', '41', '#ffffff'),
(324, 148, 7, 5, 9, '2023-04-05 17:29:08', NULL, '2023-04-05 17:29:08', NULL, 'Màu trắng', '40', '#ffffff'),
(325, 149, 7, 4, 10, '2023-04-05 17:32:06', NULL, '2023-04-05 17:32:06', NULL, 'Màu đen', '40', '#000000'),
(326, 149, 7, 6, 16, '2023-04-05 17:32:06', NULL, '2023-04-05 17:32:06', NULL, 'Màu nâu', '40', '#be7659'),
(327, 149, 7, 5, 16, '2023-04-05 17:32:06', NULL, '2023-04-05 17:32:06', NULL, 'Màu trắng', '40', '#ffffff'),
(328, 149, 7, 2, 16, '2023-04-05 17:32:06', NULL, '2023-04-05 17:32:06', NULL, 'Màu xanh dương', '40', '#0088d6'),
(329, 150, 8, 6, 0, '2023-04-05 17:33:12', NULL, '2023-04-05 17:33:12', NULL, 'Màu nâu', '41', '#be7659'),
(330, 150, 9, 6, 15, '2023-04-05 17:33:12', NULL, '2023-04-05 17:33:12', NULL, 'Màu nâu', '42', '#be7659'),
(331, 151, 8, 1, 6, '2023-04-05 17:34:31', NULL, '2023-04-05 17:34:31', NULL, 'Màu đỏ', '41', '#d61525'),
(332, 151, 8, 5, 13, '2023-04-05 17:34:31', NULL, '2023-04-05 17:34:31', NULL, 'Màu trắng', '41', '#ffffff'),
(333, 151, 9, 1, 11, '2023-04-05 17:34:31', NULL, '2023-04-05 17:34:31', NULL, 'Màu đỏ', '42', '#d61525'),
(334, 151, 9, 5, 10, '2023-04-05 17:34:31', NULL, '2023-04-05 17:34:31', NULL, 'Màu trắng', '42', '#ffffff');

-- 
-- Dumping data for table Shoes
--
INSERT INTO Shoes VALUES
(107, 'YEEZY 350 V2 V2 CLOUD WHITE', 1255000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/bccba476-4621-4679-839d-063b7ad1acdc;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/e80c9f48-9af9-479b-8bc2-52321aafa72f;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/e75603f1-b451-4bcb-b490-d53d3a938cbb;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/136facf8-ceb3-4841-bddd-ce3f4345d7f1;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/03ded36b-9f7b-4062-9a0b-72782d947b2d', 2, 1, '2023-04-05 15:53:09', NULL, '2023-04-05 15:53:09', NULL, 'Hiện đại', 'Adidas', NULL),
(108, 'YEEZY BOOST 350 V2 SLATE CORE BLACK', 1255000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/a6c7f647-d6fa-4763-8f52-08178188598f;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/5174e621-b9b7-4728-b707-e55aa8662b9a;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/a7838add-4b0a-4cde-8121-2210e96c87f7;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/122ee83e-56c7-4bd9-9eed-5d30accf792f;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/9c9c6627-1bdc-477d-8f75-13a266fdbd45', 2, 1, '2023-04-05 15:56:28', NULL, '2023-04-05 15:56:28', NULL, 'Hiện đại', 'Adidas', NULL),
(109, 'YEEZY BOOST 350 V2 ‘ZYON’', 1279000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/9d85b2c1-a85b-455a-8652-97c6ae108a20;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/866cd5e2-ae57-4488-8c9b-6b4340dac075;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/a464735e-79d5-45b2-8633-6fc56f8d28f4;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/1a51080d-466d-40ee-8922-f6f1277c5de2;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/47000549-00d8-45b5-a738-721e62f97a21;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/00962b85-40a9-4b4d-bb6f-5139a20f584d;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/4dea7fe4-4910-47d4-a17a-1a507c4b7734', 2, 1, '2023-04-05 15:59:02', NULL, '2023-04-05 15:59:02', NULL, 'Hiện đại', 'Adidas', NULL),
(110, 'YEEZY BOOST 700 INERTIA', 1295000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/ed8023f8-6d36-4e08-9f82-a2e12dfad814;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/613d190c-2d4b-449f-99b3-3a1681bd8324;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/c162af37-d940-49b5-96bd-dab4bac2bda4;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/4df09344-ba64-483e-8b68-c726597294bd;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/44013f9a-1730-4046-a76f-5b131773731f', 1, 1, '2023-04-05 16:00:49', NULL, '2023-04-05 16:00:49', NULL, 'Giày thể thao', 'Adidas', NULL),
(111, 'ADIDAS YEEZY BOOST 700 MAUVE', 1295000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/e20be19c-ca1e-4120-89f7-667f95b5b7f8;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/8f26ae7a-4705-43cf-9dbf-530408d55ca4', 1, 1, '2023-04-05 16:04:14', NULL, '2023-04-05 16:04:14', NULL, 'Giày thể thao', 'Adidas', NULL),
(112, 'ADIDAS STAN SMITH FAIRWAY', 647500.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/6f4084ce-8e91-46a8-b599-64cc148ed934;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/66c1a0e3-3067-43e3-ac04-83bb80359523;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/a8cd837f-3a89-4c74-8ddd-59d439be1bd5;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/679cec63-d7da-48c1-b4ad-1e3cad154bd3', 1, 1, '2023-04-05 16:07:13', NULL, '2023-04-05 16:07:13', NULL, 'Giày thể thao', 'Adidas', NULL),
(113, 'ADIDAS ULTRA BOOST 4.0 GREY FOUR', 597500.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/f805604a-1179-43a0-bd14-2f45cc2dd205;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/22a5361f-1fb8-4d20-b1dd-3ebe4a47324a;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/1e611e46-8ec4-4d8e-af2b-b5abcaec049d', 1, 1, '2023-04-05 16:10:02', NULL, '2023-04-05 16:10:02', NULL, 'Giày thể thao', 'Adidas', NULL),
(114, 'ADIDAS PROPHERE TRIPLE WHITE', 597500.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/4ffdbec1-8c6c-4fd9-9ec9-26587ae7184a;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/57d73764-1c1f-4765-af25-6cb9c5c4fa0a', 1, 1, '2023-04-05 16:11:46', NULL, '2023-04-05 16:11:46', NULL, 'Giày thể thao', 'Adidas', NULL),
(115, 'ADIDAS ALPHABOUNCE INSTINCT LINEN', 388500.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/8540a8a3-f540-4197-8d59-98bd67d1412c;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/abbca581-ca7d-4d71-a437-8a946846363c;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/79ba820e-7b4b-491b-9085-363f050899d6', 1, 1, '2023-04-05 16:13:13', NULL, '2023-04-05 16:13:13', NULL, 'Giày thể thao', 'Adidas', NULL),
(116, 'ADIDAS ALPHABOUNCE BEYOND CLOUD WHITE', 895000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/3edbd762-6488-4943-a9bd-4b3a3ea175bf;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/5eb51190-3a23-49d8-be96-20f7170621e7;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/69306767-2719-4032-be40-e4734ef881b2;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/9f738806-b790-447f-8185-598f50cac5af', 1, 1, '2023-04-05 16:15:38', NULL, '2023-04-05 16:15:38', NULL, 'Giày thể thao', 'Adidas', NULL),
(117, 'NIKE AIR FORCE 1 LOW WHITE/BROWN', 1195000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/a5e95ba4-94cc-437b-9b95-9fe31bafe3a0;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/ea660830-2a2e-4324-832d-2f70d6610ae3;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/61206b7f-04c6-4462-8952-43d5f39c0e72;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/4585b1dd-1f93-40f3-9d02-ed26a3ef8216', 1, 2, '2023-04-05 16:19:10', NULL, '2023-04-05 16:19:10', NULL, 'Giày thể thao', 'Nike', NULL),
(118, 'AIR JORDAN 1 MID “ARMORY NAVY”', 1295000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/c10cf2b5-bd46-4e78-aece-a301b0527b76;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/ad838c06-a099-413f-b7ab-b14235974f6c;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/570ff1b1-e722-4dba-9499-cb9ed4dec1d3;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/9f0b04dd-5c4a-4cdd-92e0-37819858e649;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/31b23e25-adbf-447c-bfc0-fc025fb81d84', 1, 2, '2023-04-05 16:22:06', NULL, '2023-04-05 16:22:06', NULL, 'Giày thể thao', 'Nike', NULL),
(119, 'AIR JORDAN 1 RETRO HIGH OG ‘STAGE HAZE’', 1322000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/10e3d344-4cac-4cff-8923-87b9f0eede92;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/45e18edd-add8-41a1-8d7c-d389bc7e3129;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/de1f4cc2-31e7-4a9e-b18e-11ed627c4736;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/42a1b322-2e87-47b0-aaec-5011639333ec;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/2ba1337b-304b-4f8c-8fd5-263590fe6606', 1, 2, '2023-04-05 16:24:01', NULL, '2023-04-05 16:24:01', NULL, 'Giày thể thao', 'Nike', NULL),
(120, 'AIR JORDAN 1 LOW ‘FRENCH BLUE’', 1289000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/7a717aea-b025-44ac-85ca-33bfc7543d1f;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/4806c0b7-c6d9-445e-bb7d-085c168be071;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/b14de975-6dc5-42ef-85c1-3548f312f0c4;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/eda607f9-676f-42df-b147-120ca00028cc;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/1ecb4b5f-7c3d-4ca0-bae1-6687cba73702', 1, 2, '2023-04-05 16:25:33', NULL, '2023-04-05 16:25:33', NULL, 'Giày thể thao', 'Nike', NULL),
(121, 'AIR JORDAN 1 LOW ‘FRENCH BLUE’', 1295000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/d225f8f3-bef8-42fd-ba1b-2a3886a8ac4a;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/e951e2f8-5c6e-4f80-b9ed-9202c14d3603;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/5983e309-be1b-4d3b-b608-84d25dfaa67c;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/33674110-f79a-4537-8732-a8cf150c0b3c;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/29dd98ac-94cb-4353-8597-5b2f7b5e6551', 1, 2, '2023-04-05 16:27:24', NULL, '2023-04-05 16:27:24', NULL, 'Giày thể thao', 'Nike', NULL),
(122, 'AIR JORDAN 1 RETRO LOW ‘ATMOSPHERE’', 1279000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/6c245375-4fa2-4692-83c6-1c7a4f4b6a04;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/11098468-abb1-4675-b27a-7b776a2b839f;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/d3a1711b-e788-4f15-95fd-d2e407170470;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/206afcbb-e5b8-4b25-b95a-56cc5881aee3', 1, 2, '2023-04-05 16:33:07', NULL, '2023-04-05 16:33:07', NULL, 'Giày thể thao', 'Nike', NULL),
(123, 'AIR MAX 270 BLUE NAVY', 1295000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/c723dd51-2176-44ff-a083-b098bfd35f23;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/b8d3775e-a9da-43c6-8d5d-745eb5fed6b8;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/2f4871aa-6c78-4a18-8483-147a4468a7e4;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/39740dee-08a7-44d2-9f9e-4702ce195edb', 1, 2, '2023-04-05 16:35:22', NULL, '2023-04-05 16:35:22', NULL, 'Giày thể thao', 'Nike', NULL),
(124, 'NIKE AIR MAX 270 SEPIA STONE', 1295000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/4db90106-2c8f-40e7-8da4-ea3852b3cd59;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/3c17abec-a721-485e-ad95-2c931554c903;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/de485732-2f2f-4273-a6f8-b214181702d2;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/3616e5e7-a965-47f4-ab6e-1f7ceaac590f;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/6e1970fd-201f-40ca-91ed-c609077080db', 1, 2, '2023-04-05 16:36:45', NULL, '2023-04-05 16:36:45', NULL, 'Giày thể thao', 'Nike', NULL),
(125, 'NIKE AIR MAX 90 SURPLUS “DESERT CAMO”', 1295000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/8abcec4d-6073-4c98-856e-989d439066a3;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/a50b8a63-a8b9-4f3c-8438-a8a339717e3b;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/a8d8ddf7-20ad-4479-8a09-6a522ea8d166;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/b19a7ac6-c93b-4f45-8240-70439af419d4', 1, 2, '2023-04-05 16:37:52', NULL, '2023-04-05 16:37:52', NULL, 'Giày thể thao', 'Nike', NULL),
(126, 'MLB BIGBALL CHUNKY A NEW YORK YANKEES BEIGE', 1095000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/70532518-f1c1-444b-8005-44d5263eca4a;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/8592c204-1ab5-4354-8d92-bcda73c81333;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/a2a89693-819a-483d-83fc-175166ea07b0;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/b0e50534-2cb2-4139-8a1b-9336b16e3636;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/3863b185-4439-441c-abb5-56615f236020', 2, 3, '2023-04-05 16:40:21', NULL, '2023-04-05 16:40:21', NULL, 'Hiện đại', 'MLB', NULL),
(127, 'MLB BIGBALL CHUNKY MONOGRAM BOSTON RED SOX D.BEIGE', 945000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/520dbdce-ac89-463a-a5f9-b5afa10085e6;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/16fbe1e4-0b85-4244-a552-e59ac2ac639e;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/baf5e9d7-ffec-4e7b-be10-ad89bd094714;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/a2ffccb6-824d-4e5c-9e57-9162c202c9c3;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/4789634f-9f07-4247-bcf5-ebec4c62fcf6', 2, 3, '2023-04-05 16:41:48', NULL, '2023-04-05 16:41:48', NULL, 'Hiện đại', 'MLB', NULL),
(128, 'MLB BIGBALL CHUNKY MONOGRAM NEW YORK YANKEES BLACK', 945000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/2788bc2d-9bee-48cb-955d-1fcd42573e9c;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/254370c3-296a-4990-ab9c-befab32c9031;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/e1e74267-1665-4824-b0f9-2df87cdea6f9;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/d32d6c92-ce9f-402b-bc3b-4c32e10de3f8;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/9c0d2992-c24c-4df0-ae94-88ce5053db44', 2, 3, '2023-04-05 16:43:32', NULL, '2023-04-05 16:43:32', NULL, 'Hiện đại', 'MLB', NULL),
(129, 'MLB BIG BALL CHUNKY A NEW YORK YANKEES “WHITE GUM”', 1095000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/8fbb1607-a067-4ef3-97f4-ba2b7e8918ba;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/ffc425ad-6d3a-4d1f-907b-67342776f50c;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/2dce1930-66e1-41df-9103-c830240b3e82;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/69da56bc-c099-4321-9bef-8ebe30ac1a1f;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/519c0db0-7567-4066-aa22-350a3b4be9ce', 2, 3, '2023-04-05 16:45:05', NULL, '2023-04-05 16:45:05', NULL, 'Hiện đại', 'MLB', NULL),
(130, 'MLB BIGBALL CHUNKY PLANET NEW YORK YANKEES', 1095000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/ba1efaa7-d894-4b32-9dcf-683164176d71;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/28b6c4cb-dbc4-4075-9ae8-cf87de41cd55;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/ee9b3aa3-dd67-4928-a508-ea89e5c7611a;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/6040baca-3d8c-40de-9be6-153a761a2690', 1, 3, '2023-04-05 16:47:21', NULL, '2023-04-05 16:47:21', NULL, 'Giày thể thao', 'MLB', NULL),
(131, 'MLB BIGBALL CHUNKY VINTAGE LT NY YANKEES', 1095000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/181ef684-c1c1-481e-bcb6-f75ac2ec9de5;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/6d1fd2dd-ba24-40c6-8bd5-ec2be4ab737e;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/6ae0f631-59ea-4bac-a2e5-51ed091526da;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/0e23b9c3-ff6a-4ab2-9714-6509026d773d;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/d1c9f431-7a1e-4c55-b810-3839123cf6c0', 1, 3, '2023-04-05 16:48:42', NULL, '2023-04-05 16:48:42', NULL, 'Giày thể thao', 'MLB', NULL),
(132, 'CONVERSE RUN STAR HIKE HI TOP BLACK', 1495000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/d1d0b5ad-b4bc-4bf8-8982-2131e4798008;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/54d11803-cfdc-4eee-844f-c1b069ce6e16;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/52ffd9cc-b99d-41b1-a2ea-e9507bbbe20a;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/24d50437-c38d-46a5-b824-8e26b3695b0a;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/e49cde3e-2955-4e25-8fae-de15d3e5e6f8', 1, 4, '2023-04-05 16:50:50', NULL, '2023-04-05 16:50:50', NULL, 'Giày thể thao', 'Converse', NULL),
(133, 'CONVERSE CHUCK 70 HIGH TOP WHITE (1970S)', 995000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/47bb41eb-e74e-48cf-ad62-5fd93dc5e60e;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/33af76cc-52af-48ad-b163-c46b8d6d02cd;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/c2923f7e-0023-4670-96d8-0d15dae696ce', 1, 4, '2023-04-05 16:51:51', NULL, '2023-04-05 16:51:51', NULL, 'Giày thể thao', 'Converse', NULL),
(134, 'CONVERSE CHUCK 70 X PEACEMINUSONE (1970S)', 895000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/47dda33f-e196-4336-8190-959a6dd15cf5;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/1064097f-8d11-47e7-8a65-e3d4e12958fd;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/41782d96-9522-4405-b4c9-cadcdb4f391e;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/692f841e-9b27-4b65-b559-7456752e3e52', 3, 4, '2023-04-05 16:54:37', NULL, '2023-04-05 16:54:37', NULL, 'Cổ điển', 'Converse', NULL),
(135, 'CONVERSE CHUCK 70 HIGH TOP SUNFLOWER (1970S)', 1195000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/0b008c7d-b495-4617-ba28-23d70c5e6e54;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/bc2ea563-220e-4348-bd62-30944ea31bc3;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/4d57ae8e-0f8a-48a8-a39c-2dbe93bd3243;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/6264717d-27b3-493e-85a9-b3af2a667e9d', 4, 4, '2023-04-05 16:56:43', NULL, '2023-04-05 16:56:43', NULL, 'Old School', 'Converse', NULL),
(136, 'CONVERSE CHUCK 70 LOW TOP SUNFLOWER (1970S)', 1195000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/aa270524-862a-4adb-a011-1ca0ecae5401;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/d76b526e-a96c-45b1-b162-da655df40ced;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/d8fd3aea-8e0a-455c-b71f-2e8201e1e814;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/db855fe4-7baf-463f-84f0-22081bbeecc5', 4, 4, '2023-04-05 16:58:02', NULL, '2023-04-05 16:58:02', NULL, 'Old School', 'Converse', NULL),
(137, 'CONVERSE CHUCK TAYLOR ALL-STAR 70S OX COMME DES GARCONS PLAY BLACK (1970S CDG)', 995000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/19af51ca-07e4-4f56-9520-bf3b5adfd208;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/b0586480-fd72-4be0-aa52-9054f59cb96e;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/26690353-4007-4c76-b661-a2f7d7563c21;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/e203e4f7-e42f-4a4e-ba4a-853b7ef20609', 3, 4, '2023-04-05 16:59:57', NULL, '2023-04-05 16:59:57', NULL, 'Cổ điển', 'Converse', NULL),
(138, 'CONVERSE CHUCK TAYLOR ALL-STAR 70S HI COMME DES GARCONS PLAY WHITE (1970S CDG)', 1195000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/7301cff2-0128-4cc5-94ca-0fb9765b36c5;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/87cf7e87-7414-4f1d-bbb7-d3fb61e09d2d;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/0a50e30f-57e4-4ea8-ae15-16fe0876ba6e', 3, 4, '2023-04-05 17:01:39', NULL, '2023-04-05 17:01:39', NULL, 'Cổ điển', 'Converse', NULL),
(139, 'CONVERSE CHUCK 70 LOW TOP BLACK (1970S)', 885000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/c721e8da-0537-4c2e-a60f-b342d91d6412;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/6a13c85c-deba-4a10-8cf1-424d79bdfc29;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/91e01497-f361-4d24-b8d2-9f1ea9f773d2;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/ae1bbbc6-136a-4fb0-a1ed-a183966c4918', 3, 4, '2023-04-05 17:03:41', NULL, '2023-04-05 17:03:41', NULL, 'Cổ điển', 'Converse', NULL),
(140, 'CONVERSE CHUCK 70 LOW TOP WHITE (1970S)', 1195000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/ba821f2c-3010-48cf-aba0-453f752fe461;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/3951fdf6-9a00-49a7-8d69-41fe3d06d46e', 4, 4, '2023-04-05 17:05:29', NULL, '2023-04-05 17:05:29', NULL, 'Old School', 'Converse', NULL),
(141, 'CONVERSE CHUCK TAYLOR ALL STAR HIGH TOP OPTICAL WHITE (CLASSIC)', 895000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/bfb7d414-5227-4c8f-bd4f-e332a90f91ae;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/08d90534-6802-4da2-8777-3eaa967a2ac4;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/92ffd943-0777-4bab-8c1a-7eec0e52a73c;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/a2ca6bf9-61a5-4568-875e-633d96a8bac1', 4, 4, '2023-04-05 17:10:30', NULL, '2023-04-05 17:10:30', NULL, 'Old School', 'Converse', NULL),
(142, 'VANS OG ERA VARSITY CANVAS WHITE GREEN', 895000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/971a1a61-f723-4356-8c56-1b571a447369;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/81725d01-4a10-45a9-9b3d-964f2381f481;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/498cbb1c-c2d4-498b-88e3-47a051a4ada2', 4, 5, '2023-04-05 17:15:01', NULL, '2023-04-05 17:15:01', NULL, 'Old School', 'Vanz', NULL),
(143, 'VANS OLD SKOOL CLASSIC', 647000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/3e7ca535-9b20-412a-ac44-8e714e448c4c;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/947b15fe-72ce-429c-912b-1a49aa66bab2;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/4887018e-5392-4845-acba-f055845cc044;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/2af65ce4-7125-40f7-8e59-cb31bc28fb1e', 4, 5, '2023-04-05 17:17:05', NULL, '2023-04-05 17:17:05', NULL, 'Old School', 'Vanz', NULL),
(144, 'VANS OG ERA LX ‘PUMPKIN SPICE ANTIQUE WHITE’', 895000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/8700ff3c-2d88-4fbe-a664-513f78013677;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/202f27ef-f85f-4d31-aba8-a703192dc726;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/f52b442a-c398-4885-8038-0b93ece4228c', 4, 5, '2023-04-05 17:20:19', NULL, '2023-04-05 17:20:19', NULL, 'Old School', 'Vanz', NULL),
(145, 'VANS STYLE 36 “MARSHMALLOW” RACING', 1195000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/fb869172-ad3c-4997-b000-009d65ce8c05;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/10fc74d7-7cd8-4a79-beee-df3a234f4f0c;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/98e1de0e-f044-4f42-838a-595e001fd87d;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/278acc21-ed8f-4a31-8a7f-10c1a8224be1;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/19b3b0cb-6919-473c-9eda-565f64bd19d5;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/f8f5e8e1-e2c7-4d20-b17d-ec581079ecae;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/922d5493-c91f-4345-84c7-a68d979517d1', 3, 5, '2023-04-05 17:24:06', NULL, '2023-04-05 17:24:06', NULL, 'Cổ điển', 'Vanz', NULL),
(146, 'VANS STYLE 36 AMBER', 1195000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/956848a7-4854-4995-9be7-f50ed06dad88;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/7bd2a58e-ddb7-414b-9ef8-12c3833a6c8d;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/8faf7d26-611a-43e7-9a79-d573e7f022ab;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/d5291fac-d68a-4e9d-9f95-2100d2ecca24;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/0d3afc0f-77ba-4e18-8041-7cb73c56ca09', 4, 5, '2023-04-05 17:26:25', NULL, '2023-04-05 17:26:25', NULL, 'Old School', 'Vanz', NULL),
(147, 'VANS SLIP ONS WHITE', 995000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/756ef59c-c59b-42a8-af3a-b57d76c7c1d3;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/2e253401-5534-44ef-9d87-7d465b9490e9', 4, 5, '2023-04-05 17:27:49', NULL, '2023-04-05 17:27:49', NULL, 'Old School', 'Vanz', NULL),
(148, 'VANS SLIP ONS CHECKERBOARD BLACK-WHITE', 995000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/0defd5c2-8a18-4a27-a26b-58ba85e31933', 4, 5, '2023-04-05 17:29:08', NULL, '2023-04-05 17:29:08', NULL, 'Old School', 'Vanz', 6),
(149, 'BALENCIAGA X ADIDAS TRIPLE', 1792000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/1b9e3579-f9a9-4b7e-b997-3acaead9bb28;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/7814a468-5181-4476-99de-51a389410723;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/8ed9d622-aa52-4bc7-a9b1-0d1e989b4ab1;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/d5cc3ef6-14d1-4e36-ae50-5f6a94804c98;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/7fecd72a-6294-4bd5-b63a-0173a468f09f;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/f4055b0e-db61-4067-a843-2a99db2ea467;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/ece34ef4-8828-4cb8-bcb7-01a2a3e36108', 2, 6, '2023-04-05 17:32:06', NULL, '2023-04-05 17:32:06', NULL, 'Hiện đại', 'Balenciaga', 6),
(150, 'BALENCIAGA TRIPLE S TRAINER YELLOW GREEN', 1795000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/e3526bad-80ae-42e7-9b36-b8afb3bb10e4;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/82298546-d507-4f16-abab-98847927d5a1;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/2f8eb5e5-1465-43f7-a381-0707919faad8', 2, 6, '2023-04-05 17:33:12', NULL, '2023-04-05 17:33:12', NULL, 'Hiện đại', 'Balenciaga', 6),
(151, 'BALENCIAGA TRIPLE S CLEAR SOLE', 1795000.00, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/1f997823-d309-495d-b3f0-c1c9cf6dcc49;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/56567ad8-d09a-4f23-a7fe-2ba90dda123f;https://fly-shoes.s3.ap-southeast-1.amazonaws.com/product/f2c80d80-a5cd-4d93-806f-a3691301a7cd', 2, 6, '2023-04-05 17:34:31', NULL, '2023-04-05 17:34:31', NULL, 'Hiện đại', 'Balenciaga', 6);

-- 
-- Dumping data for table PaymentInfo
--
INSERT INTO PaymentInfo VALUES
(20, 29, 'NCB', '102500000', '13997064', '2023-04-23 20:07:20', NULL, NULL, NULL),
(22, 30, 'NCB', '92500000', '13997845', '2023-04-24 13:21:54', NULL, NULL, NULL),
(24, 31, 'NCB', '362000000', '13997890', '2023-04-24 15:14:00', NULL, NULL, NULL),
(26, 32, 'NCB', '102500000', '13997893', '2023-04-24 15:19:07', NULL, NULL, NULL),
(27, 33, 'NCB', '102500000', '13999930', '2023-04-26 09:36:47', NULL, NULL, NULL),
(28, 33, 'NCB', '102500000', '13999930', '2023-04-26 09:36:47', NULL, NULL, NULL),
(29, 34, 'NCB', '182500000', '14001146', '2023-04-27 12:55:25', NULL, NULL, NULL),
(30, 34, 'NCB', '182500000', '14001146', '2023-04-27 12:55:26', NULL, NULL, NULL),
(31, 35, 'NCB', '112500000', '14001147', '2023-04-27 13:06:31', NULL, NULL, NULL),
(32, 35, 'NCB', '112500000', '14001147', '2023-04-27 13:06:31', NULL, NULL, NULL),
(33, 36, 'NCB', '112500000', '14001152', '2023-04-27 13:14:50', NULL, NULL, NULL),
(34, 36, 'NCB', '112500000', '14001152', '2023-04-27 13:14:50', NULL, NULL, NULL),
(35, 37, 'NCB', '92500000', '14001198', '2023-04-27 15:05:38', NULL, NULL, NULL),
(36, 37, 'NCB', '92500000', '14001198', '2023-04-27 15:05:38', NULL, NULL, NULL),
(37, 38, 'NCB', '102500000', '14001201', '2023-04-27 15:11:49', NULL, NULL, NULL),
(38, 38, 'NCB', '102500000', '14001201', '2023-04-27 15:11:49', NULL, NULL, NULL),
(39, 39, 'NCB', '102500000', '14001203', '2023-04-27 15:15:02', NULL, NULL, NULL),
(40, 39, 'NCB', '102500000', '14001203', '2023-04-27 15:15:03', NULL, NULL, NULL),
(41, 40, 'NCB', '122500000', '14001206', '2023-04-27 15:20:52', NULL, NULL, NULL),
(42, 40, 'NCB', '122500000', '14001206', '2023-04-27 15:20:53', NULL, NULL, NULL),
(43, 41, 'NCB', '62750000', '14001223', '2023-04-27 15:53:43', NULL, NULL, NULL),
(44, 41, 'NCB', '62750000', '14001223', '2023-04-27 15:53:44', NULL, NULL, NULL),
(45, 42, 'NCB', '132500000', '14001226', '2023-04-27 16:05:17', NULL, NULL, NULL),
(46, 42, 'NCB', '132500000', '14001226', '2023-04-27 16:05:17', NULL, NULL, NULL),
(47, 43, 'NCB', '92500000', '14001231', '2023-04-27 16:13:11', NULL, NULL, NULL),
(48, 43, 'NCB', '92500000', '14001231', '2023-04-27 16:13:12', NULL, NULL, NULL),
(49, 44, 'NCB', '112500000', '14001239', '2023-04-27 16:24:25', NULL, NULL, NULL),
(50, 44, 'NCB', '112500000', '14001239', '2023-04-27 16:24:26', NULL, NULL, NULL),
(51, 45, 'NCB', '112500000', '14001246', '2023-04-27 16:33:30', NULL, NULL, NULL),
(52, 46, 'NCB', '92550000', '14002587', '2023-05-01 10:46:16', NULL, NULL, NULL);

-- 
-- Dumping data for table OrderShoes
--
INSERT INTO OrderShoes VALUES
(24, 6, 3, 'Hùng Lê', '0866940201', 'Phường Phúc Diễn - Quận Bắc Từ Liêm - Thành phố Hà Nội', '6', '2023-04-18 19:12:15', '2023-04-18 19:12:15', '6', 1, False, 3440500),
(25, 6, 1, 'Hùng Lê', '0866940201', 'Phường Phúc Diễn - Quận Bắc Từ Liêm - Thành phố Hà Nội', '6', '2023-04-19 16:10:59', '2023-04-19 16:10:59', '6', 1, False, 1825000),
(26, 6, 2, 'Hùng Lê', '0866940201', 'Phường Phúc Diễn - Quận Bắc Từ Liêm - Thành phố Hà Nội', '6', '2023-04-23 01:16:41', '2023-04-23 01:16:41', '6', 2, True, 3620000),
(27, 6, 3, 'Hùng Lê', '0866940201', 'Phường Phúc Diễn - Quận Bắc Từ Liêm - Thành phố Hà Nội', '6', '2023-04-23 01:51:47', '2023-04-23 01:51:47', '6', 2, True, 1825000),
(28, 6, 4, 'Hùng Lê', '0866940201', 'Phường Phúc Diễn - Quận Bắc Từ Liêm - Thành phố Hà Nội', '6', '2023-04-23 19:59:27', '2023-04-23 19:59:27', '6', 2, True, 1825000),
(29, 6, 3, 'Hùng Lê', '0866940201', 'Phường Phúc Diễn - Quận Bắc Từ Liêm - Thành phố Hà Nội', '6', '2023-04-24 00:00:00', '2023-04-23 20:06:36', '6', 2, True, 1025000),
(30, 6, 4, 'Hùng Lê', '0866940201', 'Phường Phúc Diễn - Quận Bắc Từ Liêm - Thành phố Hà Nội', '6', '2023-04-24 13:20:58', '2023-04-24 13:20:58', '6', 2, True, 925000),
(31, 6, 4, 'Hùng Lê', '0866940201', 'Phường Phúc Diễn - Quận Bắc Từ Liêm - Thành phố Hà Nội', '6', '2023-04-24 15:13:10', '2023-04-24 15:13:10', '6', 2, True, 3620000),
(32, 6, 4, 'Hùng Lê', '0866940201', 'Phường Phúc Diễn - Quận Bắc Từ Liêm - Thành phố Hà Nội', '6', '2023-04-24 15:18:36', '2023-04-24 15:18:36', '6', 2, True, 1025000),
(33, 6, 1, 'Hùng Lê', '0866940201', 'Phường Phúc Diễn - Quận Bắc Từ Liêm - Thành phố Hà Nội', '6', '2023-04-26 09:35:43', '2023-04-26 09:35:43', '6', 2, True, 1025000),
(34, 13, 1, 'Lê Mạnh Hùng', '0866940201', 'Xã Thanh Mai - Huyện Thanh Oai - Thành phố Hà Nội', '13', '2023-04-27 12:54:43', '2023-04-27 12:54:43', '13', 2, True, 1825000),
(35, 18, 1, 'N9.Hùng Lê', '0866940201', 'Phường Nghĩa Đô - Quận Cầu Giấy - Thành phố Hà Nội', '18', '2023-04-27 13:05:48', '2023-04-27 13:05:48', '18', 2, True, 1125000),
(36, 19, 1, 'Hùng Lê', '0866940201', 'Xã Thanh Mai - Huyện Thanh Oai - Thành phố Hà Nội', '19', '2023-04-27 13:14:13', '2023-04-27 13:14:13', '19', 2, True, 1125000),
(37, 19, 1, 'Hùng Lê', '0866940201', 'Phường Minh Khai - Quận Bắc Từ Liêm - Thành phố Hà Nội', '19', '2023-04-27 15:05:02', '2023-04-27 15:05:02', '19', 2, True, 925000),
(38, 19, 1, 'Hùng Lê', '0866940201', 'Thị trấn Phúc Thọ - Huyện Phúc Thọ - Thành phố Hà Nội', '19', '2023-04-27 15:11:13', '2023-04-27 15:11:13', '19', 2, True, 1025000),
(39, 13, 1, 'Lê Mạnh Hùng', '0866940201', 'Xã Thanh Mai - Huyện Thanh Oai - Thành phố Hà Nội', '13', '2023-04-27 15:14:31', '2023-04-27 15:14:31', '13', 2, True, 1025000),
(40, 19, 1, 'Hùng Lê', '0866940201', 'Phường Tứ Liên - Quận Tây Hồ - Thành phố Hà Nội', '19', '2023-04-27 15:20:20', '2023-04-27 15:20:20', '19', 2, True, 1225000),
(41, 19, 1, 'Hùng Lê', '0866940201', 'Phường Phú Thượng - Quận Tây Hồ - Thành phố Hà Nội', '19', '2023-04-27 15:53:09', '2023-04-27 15:53:09', '19', 2, True, 627500),
(42, 19, 1, 'Hùng Lê', '0866940201', 'Phường Khâm Thiên - Quận Đống Đa - Thành phố Hà Nội', '19', '2023-04-27 16:04:53', '2023-04-27 16:04:53', '19', 2, True, 1325000),
(43, 19, 1, 'Hùng Lê', '0866940201', 'Phường Nghĩa Tân - Quận Cầu Giấy - Thành phố Hà Nội', '19', '2023-04-27 16:12:47', '2023-04-27 16:12:47', '19', 2, True, 925000),
(44, 19, 1, 'Hùng Lê', '0866940201', 'Phường Hàng Bạc - Quận Hoàn Kiếm - Thành phố Hà Nội', '19', '2023-04-27 16:23:50', '2023-04-27 16:23:50', '19', 2, True, 1125000),
(45, 19, 1, 'Hùng Lê', '0866940201', 'Xã Tân Hưng - Huyện Sóc Sơn - Thành phố Hà Nội', '19', '2023-04-27 16:33:02', '2023-04-27 16:33:02', '19', 2, True, 1125000),
(46, 13, 1, 'Lê Mạnh Hùng', '0866940201', 'Xã Thanh Mai - Huyện Thanh Oai - Thành phố Hà Nội', '13', '2023-05-01 10:45:43', '2023-05-01 10:45:43', '13', 2, True, 925500),
(47, 13, 1, 'Lê Mạnh Hùng', '0866940201', 'Xã Thanh Mai - Huyện Thanh Oai - Thành phố Hà Nội', '13', '2023-05-03 15:45:26', '2023-05-03 15:45:26', '13', 1, False, 1352000),
(48, 22, 1, 'hang', '0312345678', 'Xã Mông Sơn - Huyện Yên Bình - Tỉnh Yên Bái', '22', '2023-05-06 08:54:50', '2023-05-06 08:54:50', '22', 1, False, 1825000);

-- 
-- Dumping data for table OrderDetail
--
INSERT INTO OrderDetail VALUES
(24, 150, 329, 24, 1, NULL, '2023-04-18 19:12:03', '', '2023-04-18 19:12:03', '', 1795000),
(25, 151, 331, 24, 1, 6, '2023-04-18 19:12:03', '', '2023-04-18 19:12:03', '', 1615500),
(26, 151, 331, 25, 1, NULL, '2023-04-19 16:10:43', '', '2023-04-19 16:10:43', '', 1795000),
(27, 150, 329, 26, 1, NULL, '2023-04-23 01:16:20', '', '2023-04-23 01:16:20', '', 1795000),
(28, 151, 331, 26, 1, NULL, '2023-04-23 01:16:20', '', '2023-04-23 01:16:20', '', 1795000),
(29, 151, 331, 27, 1, NULL, '2023-04-23 01:51:38', '', '2023-04-23 01:51:38', '', 1795000),
(30, 151, 331, 28, 1, NULL, '2023-04-23 19:59:24', '', '2023-04-23 19:59:24', '', 1795000),
(31, 148, 324, 29, 1, NULL, '2023-04-23 20:06:33', '', '2023-04-23 20:06:33', '', 995000),
(32, 141, 295, 30, 1, NULL, '2023-04-24 13:20:54', '', '2023-04-24 13:20:54', '', 895000),
(33, 150, 329, 31, 1, NULL, '2023-04-24 15:13:01', '', '2023-04-24 15:13:01', '', 1795000),
(34, 151, 331, 31, 1, NULL, '2023-04-24 15:13:01', '', '2023-04-24 15:13:01', '', 1795000),
(35, 137, 289, 32, 1, NULL, '2023-04-24 15:18:32', '', '2023-04-24 15:18:32', '', 995000),
(36, 137, 289, 33, 1, NULL, '2023-04-26 09:35:28', '', '2023-04-26 09:35:28', '', 995000),
(37, 150, 329, 34, 1, NULL, '2023-04-27 12:54:39', '', '2023-04-27 12:54:39', '', 1795000),
(38, 130, 275, 35, 1, NULL, '2023-04-27 13:05:30', '', '2023-04-27 13:05:30', '', 1095000),
(39, 126, 262, 36, 1, NULL, '2023-04-27 13:13:38', '', '2023-04-27 13:13:38', '', 1095000),
(40, 141, 295, 37, 1, NULL, '2023-04-27 15:04:23', '', '2023-04-27 15:04:23', '', 895000),
(41, 133, 282, 38, 1, NULL, '2023-04-27 15:10:49', '', '2023-04-27 15:10:49', '', 995000),
(42, 137, 289, 39, 1, NULL, '2023-04-27 15:14:27', '', '2023-04-27 15:14:27', '', 995000),
(43, 117, 236, 40, 1, NULL, '2023-04-27 15:20:05', '', '2023-04-27 15:20:05', '', 1195000),
(44, 114, 228, 41, 1, NULL, '2023-04-27 15:40:00', '', '2023-04-27 15:40:00', '', 597500),
(45, 123, 255, 42, 1, NULL, '2023-04-27 16:04:40', '', '2023-04-27 16:04:40', '', 1295000),
(46, 134, 284, 43, 1, NULL, '2023-04-27 16:12:30', '', '2023-04-27 16:12:30', '', 895000),
(47, 126, 262, 44, 1, NULL, '2023-04-27 16:23:37', '', '2023-04-27 16:23:37', '', 1095000),
(48, 126, 262, 45, 1, NULL, '2023-04-27 16:32:48', '', '2023-04-27 16:32:48', '', 1095000),
(49, 148, 324, 46, 1, 6, '2023-05-01 10:45:35', '', '2023-05-01 10:45:35', '', 895500),
(50, 119, 241, 47, 1, NULL, '2023-05-03 15:45:24', '', '2023-05-03 15:45:24', '', 1322000),
(51, 151, 334, 48, 1, NULL, '2023-05-06 08:54:20', '', '2023-05-06 08:54:20', '', 1795000);

-- 
-- Dumping data for table EmailTemplate
--
INSERT INTO EmailTemplate VALUES
(1, 1, '<p>Fly Shoes</p><p>Địa chỉ : 298 Cầu Diễnn</p><p>SĐT : 0866940201</p>');

-- 
-- Dumping data for table Color
--
INSERT INTO Color VALUES
(1, 'Màu đỏ', '#d61525', '2001-07-09 08:56:50', '"Admin"', '1994-01-03 16:33:19', 'Yadira Villanueva'),
(2, 'Màu xanh dương', '#0088d6', '1976-08-19 05:48:34', '"Admin"', '2005-06-24 00:33:58', 'Britta Ayres'),
(3, 'Màu xanh lá', '#029c47', '2000-10-26 03:06:57', '"Admin"', '1970-01-01 01:08:43', 'Bernard Creighton'),
(4, 'Màu đen', '#000000', '2000-10-30 14:54:02', '"Admin"', '1970-01-01 00:01:08', 'Merle Reiter'),
(5, 'Màu trắng', '#ffffff', '1972-03-22 20:49:15', '"Admin"', '1976-11-19 21:45:26', 'Wilfredo Southern'),
(6, 'Màu nâu', '#be7659', '2023-04-05 00:00:00', NULL, '2023-04-05 00:00:00', NULL),
(7, 'Màu vàng', '#f3de54', '2023-04-05 00:00:00', NULL, '2023-04-05 00:00:00', NULL);

-- 
-- Dumping data for table Category
--
INSERT INTO Category VALUES
(1, 'Giày thể thao', NULL, 'NULL', '1996-06-13 08:06:45', 'Admin', '2023-04-05 00:00:00', 'Norris Calderon'),
(2, 'Hiện đại', NULL, 'NULL', '1970-01-01 00:00:07', 'Admin', '2023-04-05 00:00:00', 'Aileen Pitts'),
(3, 'Cổ điển', NULL, 'NULL', '1970-01-01 00:00:09', 'Admin', '2023-04-05 00:00:00', 'Alaine Hickey'),
(4, 'Old School', NULL, 'NULL', '1970-01-01 00:31:40', 'Admin', '2023-04-05 00:00:00', 'Trey Christopher');

-- 
-- Dumping data for table CartDetail
--
INSERT INTO CartDetail VALUES
(30, 17, '2023-04-25 16:02:28', 'Rang Bắp', '2023-04-25 16:02:28', 'Rang Bắp', 151),
(31, 17, '2023-04-25 16:02:35', 'Rang Bắp', '2023-04-25 16:02:35', 'Rang Bắp', 150),
(32, 19, '2023-04-27 17:29:23', 'Hùng Lê', '2023-04-27 17:29:23', 'Hùng Lê', 144),
(33, 21, '2023-04-29 09:00:25', 'nam', '2023-04-29 09:00:25', 'nam', 150);

-- 
-- Dumping data for table Brand
--
INSERT INTO Brand VALUES
(1, 'Adidas', 'Impossible is nothing', 'Adidas là tập đoàn đa quốc gia đến từ nước Đức, chuyên sản xuất các mặt hàng giầy dép, quần áo, phụ kiện. Tiền thân của hãng là công ty Gebruder Dassler Schuhfabrik được ra đời vào năm 1924 bởi hai anh em nhà Dassler là Adi Dassler và Rudolf.\r\nMặt hàng ch', NULL, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/brand-logo/logo-adidas.png', '2023-04-04 16:30:01', 'Admin', '1970-01-01 00:00:04', 'Abraham Acevedo', NULL),
(2, 'Nike', 'Just do it', 'Nike là một tập đoàn đa quốc gia chuyên cung cấp các sản phẩm như giày, phụ kiện, dụng cụ phục vụ cho quá trình luyện tập và thi đấu thể thao', NULL, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/brand-logo/logo-nike.jpg', '2023-04-04 16:30:01', 'Admin', '1985-04-20 23:12:47', 'Retta Lord', NULL),
(3, 'MLB', 'Were are forever faster', 'MLB là từ viết tắt của Major League Baseball có nghĩa là tổ chức thể thao chuyên nghiệp của môn bóng chày', NULL, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/brand-logo/logo-mlb.jpg', '2023-04-04 16:30:01', 'Admin', '1970-01-01 00:00:08', 'Treena Lind', NULL),
(4, 'Converse', 'Wear with everything', 'Converse là một thương hiệu giày nổi tiếng hàng đầu thế giới, với những thiết kế vượt thời gian trường tồn.', NULL, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/brand-logo/logo-converse.jpg', '2023-04-04 16:30:01', 'Admin', '2013-11-22 16:02:36', 'Hong Beaudoin', NULL),
(5, 'Vanz', 'Off The Wall', 'Thương hiệu VANS là một trong những thương hiệu giày được yêu thích nhất trên thế giới! Đặc biệt là sự yêu thích của các bạn trẻ yêu giày & giới mộ điệu.', NULL, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/brand-logo/logo-vanz.png', '2023-04-04 16:30:01', 'Admin', '1985-10-06 17:07:06', 'Jason Blackmon', NULL),
(6, 'Balenciaga', 'The power of dreams', 'Balenciaga là hãng thời trang cao cấp do Cristóbal Balenciaga, một nhà thiết kế thời trang người Tây Ban Nha, sáng lập.', NULL, 'https://fly-shoes.s3.ap-southeast-1.amazonaws.com/brand-logo/logo-balenciaga.png', '2023-04-04 16:30:01', 'Admin', '1976-06-27 21:11:59', 'Tiny Card', NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;