name: Publish Docker image to Docker Hub
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/fly-shoes-be
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Greeting
      run:
        echo "Hello world"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.MAIL_SERVER }}
        server_port: ${{ secrets.MAIL_PORT }}
        secure: false
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        to: mhung.haui.webdev@gmail.com,nguyentiendung.eddie@gmail.com
        from: mhung.haui.webdev@gmail.com
        body: Build job of ${{github.repository}} completed successfully!
        ignore_cert: true
        convert_markdown: true
        attachments: attachments.zip,git.diff,./dist/static/*.js
        priority: low
